export type PdfAppendix = "graphs" | "graphs-tables" | "none";
type ReportRow = { insurerName: string; productName: string; badges: string[]; logo: string | null; payouts: number[]; curve: { percent: number; payoutPercent: number }[]; table?: {title:string;columns:string[];rows:{cells:string[]}[]} };
type ReportOptions = { generatedAt: string; sumInsured: number; scenarios: { label: string; percent: number }[]; rows: ReportRow[]; appendix: PdfAppendix };
const escape = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const money = (value: number) => `${value.toLocaleString("cs-CZ", { maximumFractionDigits: 0 })} Kč`;

/** Fixed A4 pages keep each product row together in the PDF and printed preview. */
export function buildClientReport({ generatedAt, sumInsured, scenarios, rows, appendix }: ReportOptions): string {
  const perPage = 10;
  const summaryPageCount = Math.max(1, Math.ceil(rows.length / perPage));
  const appendixPages: string[] = [];
  const header = `<div class="pdf-brand"><img src="/icons/nadpislogo.jpg" alt="Logo Bohemika"/><div class="pdf-company"><strong>Bohemika a.s.</strong><span>Finanční poradenství</span></div><div class="pdf-doc-type">SROVNÁNÍ POJISTNÉHO PLNĚNÍ<small>${escape(generatedAt)}</small></div></div>`;
  if (appendix !== "none") for (const row of rows) {
    const max = Math.max(100, Math.ceil(Math.max(...row.curve.map(point => point.payoutPercent)) / 100) * 100);
    const x = (percent:number) => 55 + percent * 6.1;
    const y = (percent:number) => 275 - percent / max * 225;
    const path = row.curve.map((point,i) => `${i === 0 ? "M" : "L"}${x(point.percent).toFixed(2)},${y(point.payoutPercent).toFixed(2)}`).join(" ");
    const colors = ["#9171a7", "#5d9bb4", "#74a48c"];
    const grid = Array.from({length:5},(_,i)=>{const value=max*i/4;return `<line x1="55" x2="665" y1="${y(value)}" y2="${y(value)}" stroke="#eee7f4"/><text x="45" y="${y(value)+4}" text-anchor="end" fill="#9b86a7" font-size="10">${escape(value.toLocaleString("cs-CZ"))} %</text>`;}).join("");
    const labels = [0,25,50,75,100].map(value=>`<text x="${x(value)}" y="299" text-anchor="middle" fill="#a28cae" font-size="10">${value} %</text>`).join("");
    const markers = scenarios.map((scenario,i)=>{const actual=sumInsured > 0 ? row.payouts[i]/sumInsured*100 : 0;return `<line x1="${x(scenario.percent)}" x2="${x(scenario.percent)}" y1="${y(actual)}" y2="275" stroke="${colors[i%3]}" stroke-dasharray="4 4"/><circle cx="${x(scenario.percent)}" cy="${y(actual)}" r="8" fill="${colors[i%3]}" stroke="white" stroke-width="2"/><text x="${x(scenario.percent)}" y="${y(actual)+3}" text-anchor="middle" font-size="8" fill="white">${i+1}</text>`;}).join("");
    const productHeading = `<h1>${escape(row.insurerName)} · ${escape(row.productName)}</h1><p class="pdf-intro">${escape(row.badges.join(" · "))}</p>`;
    appendixPages.push(`${header}${productHeading}<h2 class="pdf-section-title">Jak roste pojistné plnění</h2><p class="pdf-intro">Graf ukazuje plnění v procentech ze sjednané pojistné částky podle rozsahu trvalých následků.</p><div class="pdf-chart"><svg viewBox="0 0 714 330" xmlns="http://www.w3.org/2000/svg"><text x="55" y="20" fill="#8f73a2" font-size="11">Plnění z pojistné částky</text>${grid}<path d="${path} L665,275 L55,275 Z" fill="#f2eaf8"/><path d="${path}" fill="none" stroke="#a17fba" stroke-width="2.5"/>${labels}${markers}<text x="360" y="325" text-anchor="middle" fill="#8f73a2" font-size="11">Rozsah trvalých následků</text></svg></div><h2 class="pdf-section-title">Příklad pro pojistnou částku ${escape(money(sumInsured))}</h2><div class="pdf-scenario-cards">${scenarios.map((scenario,i)=>`<div><small style="color:${colors[i%3]}">SCÉNÁŘ ${i+1} · ${escape(scenario.percent.toLocaleString("cs-CZ"))} % TN</small><strong>${escape(money(row.payouts[i]))}</strong><span>${escape((sumInsured > 0 ? row.payouts[i]/sumInsured*100 : 0).toLocaleString("cs-CZ",{maximumFractionDigits:2}))} % pojistné částky</span></div>`).join("")}</div><p class="pdf-explanation">Výpočet částky: pojistná částka × procento plnění ÷ 100. Procento plnění už zahrnuje progresi dané varianty; nejde o samotné procento poškození.</p>`);
    if (appendix === "graphs-tables" && row.table) {
      // Dense numeric tables use two columns; interval descriptions get a wider column.
      const dense = row.table.rows.every(item => item.cells.every(cell => cell.length <= 20));
      const rowsPerColumn = dense ? 23 : 18;
      const columns = dense ? 2 : 1;
      const rowsPerPage = rowsPerColumn * columns;
      for (let offset=0;offset<row.table.rows.length;offset+=rowsPerPage) {
        const blocks = Array.from({length:columns},(_,column)=>row.table!.rows.slice(offset+column*rowsPerColumn,offset+(column+1)*rowsPerColumn)).filter(block=>block.length);
        appendixPages.push(`${header}${productHeading}<h2 class="pdf-section-title">${escape(row.table.title)}</h2><p class="pdf-intro">Úplná tabulka progrese · řádky ${offset+1}–${Math.min(row.table.rows.length,offset+rowsPerPage)} z ${row.table.rows.length}</p><div class="pdf-progression-grid">${blocks.map(block=>`<table class="pdf-progression"><thead><tr>${row.table!.columns.map(column=>`<th>${escape(column)}</th>`).join("")}</tr></thead><tbody>${block.map(item=>`<tr>${item.cells.map(cell=>`<td>${escape(cell)}</td>`).join("")}</tr>`).join("")}</tbody></table>`).join("")}</div>`);
      }
    }
  }
  const pageCount = summaryPageCount + appendixPages.length;
  const maxima = scenarios.map((_, i) => Math.max(0, ...rows.map(row => row.payouts[i])));
  return `<div class="pdf-root"><style>
    .pdf-root{font-family:Arial,Helvetica,sans-serif;color:#493452;background:#fff;width:794px;font-size:12px;line-height:1.4}
    .pdf-root *{box-sizing:border-box}.pdf-page{position:relative;width:794px;height:1123px;padding:38px 40px 100px;background:white;overflow:hidden;page-break-after:always}
    .pdf-brand{display:flex;justify-content:space-between;align-items:center;gap:18px;padding-bottom:12px;border-bottom:2px solid #dfeef5;color:#9e8aaa;font-size:10px}.pdf-brand img{width:94px;height:60px;object-fit:contain}.pdf-company{flex:1}.pdf-company strong{display:block;color:#536575;font-size:19px;font-weight:600;letter-spacing:-.02em}.pdf-company span{display:block;color:#8fa2ae;font-size:10px;margin-top:3px}.pdf-doc-type{text-align:right;font-size:9px;letter-spacing:.05em;color:#8c759a}.pdf-doc-type small{display:block;margin-top:6px;font-size:9px;letter-spacing:0;color:#ad9bb5}
    .pdf-page h1{font-size:29px;line-height:1.15;letter-spacing:-.04em;margin:18px 0 8px;color:#46304f}.pdf-intro{font-size:11px;color:#9a84a6;margin:0 0 12px}
    .pdf-parameters{display:flex;gap:10px;margin-bottom:16px}.pdf-parameter{flex:1;background:#f7f2fa;border:1px solid #e9dff0;border-radius:10px;padding:12px}.pdf-parameter small{display:block;font-size:9px;color:#9f87ae;margin-bottom:4px}.pdf-parameter strong{font-size:18px;color:#74528a;white-space:nowrap}
    .pdf-page table{width:100%;border-collapse:collapse;table-layout:fixed}.pdf-page th{padding:10px 8px;background:#f2eaf7;color:#79598c;font-weight:600;font-size:10px;text-align:right;border-bottom:1px solid #ddcce8}.pdf-page th:first-child{text-align:left;width:43%}.pdf-page th small{display:block;font-weight:400;color:#a18caf;font-size:9px}
    .pdf-page td{padding:10px 8px;height:55px;border-bottom:1px solid #eee6f3;vertical-align:middle;text-align:right;font-size:13px;font-weight:600;color:#70517f}.pdf-page td:first-child{text-align:left;font-size:11px;font-weight:400}.pdf-page tr:nth-child(even) td{background:#fdfbfe}.pdf-row-name{display:flex;gap:9px;align-items:center}.pdf-row-name img{width:35px;max-height:24px;object-fit:contain}.pdf-row-name strong{display:block;color:#4c3658;font-size:11px}.pdf-row-name span{display:block;color:#967ca5;font-size:9px}.pdf-row-name small{display:block;color:#aa97b5;font-size:8px}.pdf-page td.best{color:#427562;background:#edf7f1}.pdf-page .pdf-footer{position:absolute;left:40px;right:40px;bottom:32px;border-top:1px solid #e8dfee;padding-top:13px;font-size:9px;color:#9f8aab}.pdf-footer p{margin:0 0 10px;max-width:640px}.pdf-footer div{display:flex;justify-content:space-between}
    .pdf-section-title{font-size:15px;color:#78568d;margin:24px 0 10px}.pdf-chart{border:1px solid #eadff1;border-radius:12px;padding:10px;margin:12px 0 24px}.pdf-chart svg{display:block;width:100%;height:auto}.pdf-scenario-cards{display:flex;gap:12px}.pdf-scenario-cards>div{flex:1;padding:16px 12px;border:1px solid #e7dcee;border-radius:10px;background:#faf7fd}.pdf-scenario-cards small{display:block;font-size:10px}.pdf-scenario-cards strong{display:block;font-size:20px;color:#735089;margin:12px 0 6px}.pdf-scenario-cards span{font-size:10px;color:#a18baa}.pdf-explanation{font-size:11px;color:#9c86a7;line-height:1.7;margin-top:24px;max-width:610px}.pdf-progression-grid{display:flex;gap:20px;align-items:flex-start}.pdf-progression-grid>table{flex:1;width:0}.pdf-page .pdf-progression td{height:auto;font-size:10px;padding:7px 9px;line-height:1.5}.pdf-page .pdf-progression th{font-size:10px;padding:10px 9px}.pdf-page .pdf-progression td:first-child{font-size:10px}
    @media print{.pdf-root{width:100%}.pdf-page{page-break-inside:avoid}.pdf-page:last-child{page-break-after:auto}@page{size:A4;margin:0}}
  </style>${Array.from({length:summaryPageCount},(_,page)=>`<section class="pdf-page">
    ${header}
    <h1>Trvalé následky úrazu</h1><p class="pdf-intro">${scenarios.length > 1 ? "Tři modelové situace přehledně vedle sebe." : "Přehled plnění pro zadanou pojistnou částku a rozsah následků."} ${rows.length} srovnávaných variant.</p>
    <div class="pdf-parameters"><div class="pdf-parameter"><small>POJISTNÁ ČÁSTKA</small><strong>${escape(money(sumInsured))}</strong></div>${scenarios.map((scenario,i)=>`<div class="pdf-parameter"><small>${scenarios.length > 1 ? `SCÉNÁŘ ${i+1}` : "ROZSAH NÁSLEDKŮ"}</small><strong>${escape(scenario.percent.toLocaleString("cs-CZ"))} %</strong></div>`).join("")}</div>
    <table><thead><tr><th>Pojišťovna a produkt<small>Varianta / období podmínek</small></th>${scenarios.map((scenario,i)=>`<th>${scenarios.length > 1 ? `Scénář ${i+1} · ` : "Plnění · "}${escape(scenario.percent.toLocaleString("cs-CZ"))} %<small>Částka k vyplacení</small></th>`).join("")}</tr></thead><tbody>${rows.slice(page*perPage,(page+1)*perPage).map(row=>`<tr><td><div class="pdf-row-name">${row.logo ? `<img src="${escape(row.logo)}" alt="" />` : ""}<div><strong>${escape(row.insurerName)}</strong><span>${escape(row.productName)}</span><small>${escape(row.badges.join(" · "))}</small></div></div></td>${row.payouts.map((payout,i)=>`<td${payout > 0 && payout === maxima[i] ? ' class="best"' : ""}>${escape(money(payout))}</td>`).join("")}</tr>`).join("")}</tbody></table>
    <footer class="pdf-footer"><p>Modelové srovnání při stejné pojistné částce. Skutečné plnění závisí na sjednané variantě, oceňovací tabulce a podmínkách konkrétní smlouvy. Zeleně je označeno nejvyšší plnění v daném scénáři z vybraných produktů.</p><div><span>Vytvořeno ${escape(generatedAt)}</span><span>Strana ${page+1} / ${pageCount}</span></div></footer>
  </section>`).join("")}${appendixPages.map((content,index)=>`<section class="pdf-page pdf-appendix">${content}<footer class="pdf-footer"><p>Modelový průběh plnění pro konkrétní produktovou variantu. Rozsah následků se posuzuje podle oceňovací tabulky příslušné smlouvy.</p><div><span>Bohemika a.s. · Podklady ke srovnání</span><span>Strana ${summaryPageCount+index+1} / ${pageCount}</span></div></footer></section>`).join("")}</div>`;
}
