import type { OnlineCardLocale } from "@/lib/onlineCardI18n";

export const CARE_SOURCES = {
  assessment: "https://mpsv.gov.cz/prispevek-na-peci",
  lumpSum: "https://www.cpp.cz/file/edee/dokumenty/zivotni-rizikove-a-urazove-pojisteni/brozury-pojistnych-podminek/pojisteni-neon/neon-risk/brozura-neon-risk_01_2026.pdf#page=41",
  pension: "https://www.koop.cz/pojisteni/pojisteni-osob/pojisteni-sobestacnosti-flexi/jak-se-posuzuji-stupne-nesobestacnosti",
};

export const CARE_COPY = {
  cs: {
    title: "Závislost na péči", kicker: "Podpora pro vás i vaše blízké",
    close: "Zavřít detail závislosti na péči", detail: "Každodenní pomoc a finanční jistota",
    intro: "Když kvůli nemoci nebo úrazu dlouhodobě potřebujete pomoc druhých, mění se život i rozpočet rodiny. Pojištění může pomoci zaplatit potřebnou péči a ulevit vašim blízkým.",
    stateSupportTitle: "Státní příspěvek nemusí pokrýt všechny náklady",
    stateSupportText: "Výše příspěvku na péči závisí na přiznaném stupni závislosti a dalších zákonných podmínkách. Skutečné náklady se ale odvíjejí od rozsahu potřebné pomoci a cen služeb.",
    stateSupportImpact: "Pokud náklady převýší příspěvek, rozdíl je potřeba pokrýt z příjmů, úspor či jiných zdrojů. Pojištění může při splnění podmínek pomoci tuto finanční mezeru zmenšit a ulevit rodinnému rozpočtu.",
    stateSupportSource: "MPSV · Výše a podmínky příspěvku na péči",
    definitionTitle: "Když běžné činnosti vyžadují pomoc",
    definitionText: "Při posuzování závislosti se hodnotí zvládání základních životních potřeb. Patří mezi ně například:",
    needs: ["Pohyb", "Osobní hygiena", "Oblékání", "Stravování"],
    assessmentSource: "MPSV · Jak se posuzuje závislost na péči",
    scopeTitle: "Rozhoduje sjednaný stupeň závislosti",
    scopeText: "Ne každá potřeba pomoci zakládá nárok na plnění. Některé produkty kryjí až II.–IV. stupeň závislosti, takže I. stupeň nemusí být pojištěný. Ověříme přesné podmínky i způsob doložení nároku.",
    scopeSource: "Příklad rozsahu krytí · Kooperativa",
    reasonsTitle: "Pomoc, která může ulevit celé rodině",
    reasons: [
      ["Péče doma", "Peníze na pečovatelskou službu nebo osobní asistenci, pokud vám zdravotní stav umožní zůstat doma."],
      ["Podpora pečujících blízkých", "Rezerva může pomoci, když člen rodiny kvůli péči omezí práci a domácnosti klesne příjem."],
      ["Úpravy a pomůcky", "Prostředky na úpravu koupelny, bezbariérový přístup nebo pomůcky pro každodenní fungování."],
      ["Pobytová a odlehčovací péče", "Finanční podpora může pomoci s úhradou vhodné služby a dát blízkým prostor k odpočinku."],
    ],
    paymentTitle: "Jak může být podpora vyplácena",
    lumpSumTitle: "Jednorázová částka",
    lumpSumText: "Některá pojištění vyplácejí částku najednou. Ta může posloužit k úpravám bydlení nebo jako rezerva na péči.",
    lumpSumSource: "Příklad jednorázového plnění · ČPP NEON RISK",
    pensionTitle: "Pravidelná renta",
    pensionText: "Jiné produkty poskytují pravidelnou měsíční výplatu. Její výše a doba vyplácení se řídí sjednaným pojištěním.",
    pensionSource: "Příklad měsíčního plnění · Kooperativa",
    paymentNote: "Jde o různé možnosti na trhu, nikoli automaticky o dvě plnění z jedné smlouvy.",
    checksTitle: "Co spolu ověříme",
    checks: [
      ["Rozsah a posouzení", "Pojištěné stupně, potřebné rozhodnutí či lékařské podklady a případné výluky."],
      ["Trvání ochrany", "Do jakého věku pojištění platí, případné čekací doby a jak dlouho může být plnění vypláceno."],
    ],
    planningTitle: "Plán péče i plán financí",
    planningText: "Probereme, kdo by vám mohl pomáhat, jaké služby byste chtěli využít a kolik by na ně domácnost potřebovala. Zohledníme úspory, případný státní příspěvek na péči i další pojištění. Porovnáme přitom vhodné varianty od více pojišťoven.",
    meetingCta: "Probrat zajištění potřebné péče",
  },
  en: {
    title: "Dependency on care", kicker: "Support for you and your loved ones",
    close: "Close care dependency details", detail: "Everyday assistance and financial security",
    intro: "When illness or injury means you need long-term help from others, family life and finances can change. Insurance can help pay for care and ease the load on your loved ones.",
    stateSupportTitle: "The state care allowance may not cover every cost",
    stateSupportText: "The allowance depends on the recognised level of dependency and other statutory conditions. Actual costs depend on the amount of help needed and the prices of services.",
    stateSupportImpact: "If costs exceed the allowance, the difference needs to come from income, savings or other sources. Subject to its terms, insurance can help reduce this gap and ease pressure on the family budget.",
    stateSupportSource: "MPSV · Care allowance amounts and conditions (Czech)",
    definitionTitle: "When everyday activities require help",
    definitionText: "Care dependency is assessed by looking at the ability to meet basic everyday needs. Examples include:",
    needs: ["Moving around", "Personal hygiene", "Getting dressed", "Eating and drinking"],
    assessmentSource: "MPSV · How care dependency is assessed (Czech)",
    scopeTitle: "The insured level of dependency matters",
    scopeText: "Needing help does not always qualify for a benefit. Some products cover only levels II–IV, so level I may not be insured. We will check the exact conditions and evidence required.",
    scopeSource: "Example scope of cover · Kooperativa (Czech)",
    reasonsTitle: "Help that can support the whole family",
    reasons: [
      ["Care at home", "Money towards a care service or personal assistance if your health allows you to remain at home."],
      ["Support for family carers", "A reserve can help when a family member reduces their working hours to provide care, lowering household income."],
      ["Adaptations and aids", "Funds for bathroom adaptations, accessible entrances or aids for everyday life."],
      ["Residential and respite care", "Financial support can help pay for suitable services and give loved ones time to rest."],
    ],
    paymentTitle: "How support can be paid",
    lumpSumTitle: "A lump sum",
    lumpSumText: "Some policies pay an amount in one instalment. It could fund home adaptations or provide a reserve for care.",
    lumpSumSource: "Example lump-sum cover · ČPP NEON RISK (Czech)",
    pensionTitle: "Regular payments",
    pensionText: "Other products provide monthly payments. Their amount and duration depend on the insurance arranged.",
    pensionSource: "Example monthly benefits · Kooperativa (Czech)",
    paymentNote: "These are different market options, not automatically two benefits under one policy.",
    checksTitle: "What we will check together",
    checks: [
      ["Scope and assessment", "Insured levels, required decisions or medical evidence, and any exclusions."],
      ["Duration of protection", "The age at which cover ends, any waiting periods and how long benefits can be paid."],
    ],
    planningTitle: "A plan for care and finances",
    planningText: "We will discuss who could help you, which services you would want and how much your household would need. We will consider savings, any state care allowance and other insurance. We will compare suitable options from several insurers.",
    meetingCta: "Discuss protection for care needs",
  },
  uk: {
    title: "Залежність від стороннього догляду", kicker: "Підтримка для вас і ваших близьких",
    close: "Закрити опис страхування залежності від догляду", detail: "Щоденна допомога та фінансова впевненість",
    intro: "Коли через хворобу чи травму ви тривалий час потребуєте допомоги інших, змінюються життя й бюджет родини. Страхування може допомогти оплатити догляд і полегшити навантаження на близьких.",
    stateSupportTitle: "Державна допомога може не покрити всіх витрат",
    stateSupportText: "Розмір допомоги на догляд залежить від встановленого ступеня залежності та інших законодавчих умов. Фактичні витрати визначаються обсягом необхідної допомоги й цінами послуг.",
    stateSupportImpact: "Якщо витрати перевищують допомогу, різницю потрібно покривати з доходів, заощаджень або інших джерел. За дотримання умов страхування виплата може допомогти зменшити цю різницю та навантаження на сімейний бюджет.",
    stateSupportSource: "MPSV · Розмір та умови допомоги на догляд (чеською)",
    definitionTitle: "Коли щоденні справи потребують допомоги",
    definitionText: "Під час оцінювання залежності визначають здатність задовольняти основні життєві потреби. Серед них, наприклад:",
    needs: ["Пересування", "Особиста гігієна", "Одягання", "Харчування"],
    assessmentSource: "MPSV · Оцінювання залежності від догляду (чеською)",
    scopeTitle: "Важливий застрахований ступінь залежності",
    scopeText: "Не кожна потреба в допомозі дає право на виплату. Деякі продукти покривають лише II–IV ступені, тому I ступінь може не бути застрахований. Перевіримо точні умови й необхідні підтвердження.",
    scopeSource: "Приклад обсягу покриття · Kooperativa (чеською)",
    reasonsTitle: "Допомога, яка підтримує всю родину",
    reasons: [
      ["Догляд удома", "Кошти на службу догляду або особисту допомогу, якщо стан здоров’я дозволяє залишатися вдома."],
      ["Підтримка близьких, які доглядають", "Резерв може допомогти, коли член родини менше працює через догляд і дохід домогосподарства знижується."],
      ["Облаштування та допоміжні засоби", "Кошти на пристосування ванної кімнати, безбар’єрний доступ або засоби для повсякденного життя."],
      ["Заклади догляду та тимчасова допомога", "Фінансова підтримка може допомогти оплатити відповідні послуги й дати близьким час на відпочинок."],
    ],
    paymentTitle: "Як може виплачуватися підтримка",
    lumpSumTitle: "Одноразова сума",
    lumpSumText: "Деякі поліси передбачають одноразову виплату. Вона може допомогти пристосувати житло або створити резерв на догляд.",
    lumpSumSource: "Приклад одноразової виплати · ČPP NEON RISK (чеською)",
    pensionTitle: "Регулярні виплати",
    pensionText: "Інші продукти передбачають щомісячні виплати. Їхній розмір і тривалість залежать від укладеного договору страхування.",
    pensionSource: "Приклад щомісячних виплат · Kooperativa (чеською)",
    paymentNote: "Це різні можливості на ринку, а не автоматично дві виплати за одним договором.",
    checksTitle: "Що перевіримо разом",
    checks: [
      ["Обсяг та оцінювання", "Застраховані ступені, необхідні рішення чи медичні документи та можливі виключення."],
      ["Тривалість захисту", "До якого віку діє страхування, можливі періоди очікування та тривалість виплат."],
    ],
    planningTitle: "План догляду та фінансів",
    planningText: "Обговоримо, хто міг би вам допомагати, якими послугами ви хотіли б користуватися та скільки коштів потрібно родині. Врахуємо заощадження, можливу державну допомогу на догляд та інше страхування. Порівняємо відповідні варіанти від кількох страховиків.",
    meetingCta: "Обговорити фінансовий захист на випадок догляду",
  },
} satisfies Record<OnlineCardLocale, unknown>;
