import type { OnlineCardLocale } from "@/lib/onlineCardI18n";

export const DAILY_ACCIDENT_SOURCES = {
  product: "https://www.allianz.cz/cs_CZ/ms/likvidace-zivot/denni-odskodne.html",
  terms: "https://www.cpp.cz/file/edee/dokumenty/zivotni-rizikove-a-urazove-pojisteni/brozury-pojistnych-podminek/pojisteni-neon/neon-risk/brozura-neon-risk_01_2026.pdf",
};

export const DAILY_ACCIDENT_COPY = {
  cs: {
    title: "Denní odškodné za úraz", kicker: "Finanční pomoc při léčení", close: "Zavřít detail denního odškodného", detail: "Jak funguje plnění a progrese",
    badge: "Prostor na zotavení", intro: "Úraz může na čas změnit váš běžný život. Denní odškodné přináší finanční pomoc za léčení jeho následků — například na výdaje, které ani během zotavování nepočkají.",
    calculationTitle: "O výši plnění rozhoduje i tabulka", calculation: "Základem je sjednaná denní částka a počet dnů uznaných pojišťovnou. Oceňovací tabulky přiřazují jednotlivým poraněním počet dnů nebo jejich maximum. Skutečná délka léčení proto nemusí odpovídat počtu proplacených dnů.",
    formula: "Denní částka × uznané dny", formulaNote: "Základní výpočet bez progrese; podmínky a limity se mezi produkty liší.",
    timingTitle: "Od kdy lze získat plnění?",
    modernTitle: "Plnění může začínat už od 1. dne", modernText: "U vybraných produktů s tabulkovým plněním lze nárok posoudit už podle prvotní lékařské dokumentace. Jiné varianty vycházejí z doložené doby léčení. „Od 1. dne“ označuje placené dny, nikoli okamžité připsání peněz.",
    olderTitle: "Minimální délka a zpětné plnění", olderText: "Některé varianty vyžadují určitou minimální dobu léčení. Porovnáme, kdy vzniká nárok a zda se pak plní zpětně od prvního dne, nebo až od sjednaného dne. Kratší léčení nemusí splnit podmínky výplaty.",
    recommendationKicker: "Výběr mezi pojišťovnami", recommendationTitle: "Co porovnáváme u úrazového pojištění", recommendation: "Projdeme nabídky více pojišťoven podle vaší práce, aktivit a rozpočtu. Vedle ceny porovnáme, jaké události smlouva kryje a kolik by vyplatila za konkrétní poranění.",
    advantages: [["Rozsah krytí", "Definice úrazu, výluky a krytí vašich sportů. Rozšíření některých produktů nemusí být součástí jiných."], ["Oceňovací tabulky", "Kolik dnů pojišťovna uzná, jaká je minimální doba léčení a jaké podklady vyžaduje."], ["Průběh progrese", "Zda se denní částka zvyšuje, od kdy a jak. Samotný maximální násobek nevystihuje celý výpočet."]],
    progressionTitle: "Jak funguje progresivní plnění", progression: "U variant s progresí může s počtem uznaných dnů růst i plnění. Každá pojišťovna může mít jiné hranice a způsob výpočtu.",
    daysHeading: "Uznané dny léčení", rateHeading: "Výše denní částky", periods: ["1.–80. den", "81.–120. den", "121.–160. den", "161.–240. den", "241.–365. den"],
    progressionNote: "V této ukázce se pásma počítají zvlášť a vyšší násobek platí jen pro dny v daném pásmu. Sazba 500 % se neuplatňuje na celé léčení zpětně. Jde o podmínky NEON RISK 01/2026; pravidla ostatních produktů mohou být jiná.",
    exampleTitle: "Příklad: 300 Kč denně a 100 uznaných dnů", withoutProgression: "Bez progrese", withProgression: "S progresí ČPP", exampleCalculation: "80 × 300 Kč + 20 × 600 Kč = 36 000 Kč", exampleNote: "Modelový výpočet při splnění podmínek, bez případného krácení. Sto dnů musí být uznáno podle oceňovací tabulky; samotné léčení po tuto dobu nestačí.",
    checkTitle: "Co spolu ještě ověříme", checks: [["Vaši konkrétní smlouvu", "Denní částku, oceňovací tabulku, sporty a výluky. Porovnáme i verzi podmínek, která se na vaši smlouvu vztahuje."], ["Omezení u některých poranění", "Požadavky na lékařské zprávy či zobrazovací vyšetření, limity plnění a pravidla pro opakované úrazy. Podmínky se mezi produkty liší."]],
    productSource: "Allianz · Jak se posuzuje denní odškodné", termsSource: "Zdroj ukázky · ČPP NEON RISK 01/2026", meetingCta: "Probrat úrazové pojištění",
    progressionExample: "Ukázka konkrétní varianty · ČPP NEON RISK",
  },
  en: {
    title: "Daily accident benefit", kicker: "Financial help during recovery", close: "Close daily accident benefit details", detail: "How benefits and progression work",
    badge: "Time to recover", intro: "An injury can disrupt everyday life. Daily accident benefit provides financial help while you recover from its effects — for example, with expenses that cannot wait.",
    calculationTitle: "The insurer’s assessment table matters", calculation: "The starting point is your insured daily amount and the number of days recognised by the insurer. Assessment tables assign a number of days or a maximum to each injury. Your actual treatment period may therefore differ from the number of days paid.",
    formula: "Daily amount × recognised days", formulaNote: "Basic calculation without progression; conditions and limits vary by product.",
    timingTitle: "When can cover start?",
    modernTitle: "Benefits can start from day 1", modernText: "Some products with table-based benefits can assess a claim using the initial medical records. Other options use the documented treatment period. “From day 1” describes the days paid, not an immediate transfer of money.",
    olderTitle: "Minimum duration and retrospective payment", olderText: "Some options require a minimum treatment period. We will compare when entitlement starts and whether benefits then cover earlier days from day one or only the days after the agreed starting point. Shorter treatment may not qualify.",
    recommendationKicker: "Choosing between insurers", recommendationTitle: "What we compare in accident cover", recommendation: "We will review options from several insurers against your work, activities and budget. Alongside the price, we will compare the events covered and the amount payable for specific injuries.",
    advantages: [["Scope of cover", "The injury definition, exclusions and cover for your sports. Extensions offered by some products may not be included in others."], ["Assessment tables", "How many days the insurer recognises, the minimum treatment period and the evidence required."], ["Progression rules", "Whether the daily amount increases, when and how. The maximum multiplier alone does not explain the calculation."]],
    progressionTitle: "How progressive benefits work", progression: "With progressive options, benefits can increase as the number of recognised days rises. Insurers may use different thresholds and calculation methods.",
    daysHeading: "Recognised treatment days", rateHeading: "Daily amount paid", periods: ["Days 1–80", "Days 81–120", "Days 121–160", "Days 161–240", "Days 241–365"],
    progressionNote: "In this example, bands are calculated separately and a higher multiplier applies only to days within its band. The 500% rate does not apply retrospectively to the whole period. These are NEON RISK terms dated 01/2026; other products may have different rules.",
    exampleTitle: "Example: CZK 300 a day, 100 recognised days", withoutProgression: "Without progression", withProgression: "With ČPP progression", exampleCalculation: "80 × CZK 300 + 20 × CZK 600 = CZK 36,000", exampleNote: "Illustrative calculation assuming policy conditions are met and no reductions apply. All 100 days must be recognised under the assessment table; being treated for that long alone is not enough.",
    checkTitle: "What we will also check", checks: [["Your specific policy", "The daily amount, assessment table, sports and exclusions. We will also compare the terms applicable to your policy version."], ["Limits for certain injuries", "Requirements for medical reports or imaging, benefit limits and rules for repeated injuries. Conditions differ by product."]],
    productSource: "Allianz · Assessing daily accident benefits (Czech)", termsSource: "Example source · ČPP NEON RISK 01/2026 (Czech)", meetingCta: "Discuss accident cover",
    progressionExample: "One product example · ČPP NEON RISK",
  },
  uk: {
    title: "Щоденна виплата за травму", kicker: "Фінансова допомога під час лікування", close: "Закрити опис щоденної виплати", detail: "Як працюють виплати та прогресія",
    badge: "Час на відновлення", intro: "Травма може тимчасово змінити звичне життя. Щоденна виплата допомагає фінансово під час лікування її наслідків — наприклад, покрити витрати, які не можна відкласти.",
    calculationTitle: "Важлива й таблиця страховика", calculation: "Основою є застрахована денна сума та кількість днів, визнаних страховиком. Оцінювальні таблиці визначають для кожної травми кількість днів або їхню максимальну кількість. Фактичне лікування може тривати довше, ніж оплачуваний період.",
    formula: "Денна сума × визнані дні", formulaNote: "Базовий розрахунок без прогресії; умови та ліміти залежать від продукту.",
    timingTitle: "Від якого дня можливе покриття?",
    modernTitle: "Виплати можуть охоплювати вже 1-й день", modernText: "У деяких продуктах із табличними виплатами випадок можна оцінити за первинними медичними документами. Інші варіанти враховують підтверджений строк лікування. «З 1-го дня» означає оплачувані дні, а не негайне надходження коштів.",
    olderTitle: "Мінімальна тривалість і виплата за попередні дні", olderText: "Деякі варіанти вимагають мінімального строку лікування. Порівняємо, коли виникає право на виплату та чи охоплює вона попередні дні від першого дня або лише період від узгодженого дня. Коротше лікування може не давати права на виплату.",
    recommendationKicker: "Вибір між страховиками", recommendationTitle: "Що порівнюємо у страхуванні від травм", recommendation: "Розглянемо пропозиції кількох страховиків з огляду на вашу роботу, заняття та бюджет. Крім ціни, порівняємо покриті події й розмір виплат за конкретні травми.",
    advantages: [["Обсяг покриття", "Визначення травми, виключення та покриття ваших видів спорту. Розширення окремих продуктів можуть бути відсутні в інших."], ["Оцінювальні таблиці", "Скільки днів визнає страховик, мінімальний строк лікування та необхідні документи."], ["Правила прогресії", "Чи зростає денна сума, коли й у який спосіб. Сам максимальний множник не пояснює весь розрахунок."]],
    progressionTitle: "Як працює прогресивна виплата", progression: "У варіантах із прогресією виплата може зростати зі збільшенням кількості визнаних днів. Страховики можуть застосовувати різні межі та способи розрахунку.",
    daysHeading: "Визнані дні лікування", rateHeading: "Розмір денної суми", periods: ["1–80-й день", "81–120-й день", "121–160-й день", "161–240-й день", "241–365-й день"],
    progressionNote: "У цьому прикладі діапазони розраховуються окремо, а вищий множник діє лише для днів відповідного діапазону. Ставка 500 % не поширюється на весь період заднім числом. Це умови NEON RISK 01/2026; інші продукти можуть мати інші правила.",
    exampleTitle: "Приклад: 300 Kč на день і 100 визнаних днів", withoutProgression: "Без прогресії", withProgression: "З прогресією ČPP", exampleCalculation: "80 × 300 Kč + 20 × 600 Kč = 36 000 Kč", exampleNote: "Умовний розрахунок за виконання умов договору, без можливого зменшення виплати. Усі 100 днів мають бути визнані за таблицею; самої тривалості лікування недостатньо.",
    checkTitle: "Що ще перевіримо разом", checks: [["Ваш конкретний договір", "Денну суму, оцінювальну таблицю, спорт і виключення. Також порівняємо версію умов, що діє для вашого договору."], ["Обмеження для окремих травм", "Вимоги до медичних звітів чи обстежень, ліміти виплат і правила для повторних травм. Умови залежать від продукту."]],
    productSource: "Allianz · Оцінювання щоденних виплат (чеською)", termsSource: "Джерело прикладу · ČPP NEON RISK 01/2026 (чеською)", meetingCta: "Обговорити страхування від травм",
    progressionExample: "Приклад окремого варіанта · ČPP NEON RISK",
  },
} satisfies Record<OnlineCardLocale, unknown>;
