import type { OnlineCardLocale } from "@/lib/onlineCardI18n";

export const DEATH_SOURCE = "https://www.cpp.cz/slovnik-pojmu/zivotni-a-urazove-pojisteni";

export const DEATH_COPY = {
  cs: {
    kicker: "Pojištění pro případ smrti",
    title: "Finanční jistota pro ty, kteří zůstanou",
    close: "Zavřít detail pojištění pro případ smrti",
    detail: "Zajištění blízkých a závazků",
    intro: "Ztrátu blízkého člověka peníze nenahradí. Mohou ale rodině pomoci zvládnout výdaje a dát jí čas přizpůsobit se nové situaci.",
    benefits: [
      ["Důstojné rozloučení", "Prostředky na pohřeb, rozloučení a související jednorázové výdaje."],
      ["Zajištění pozůstalých", "Peníze na bydlení, energie, jídlo a další běžné potřeby při výpadku příjmu."],
      ["Hypotéka a další závazky", "Prostředky na doplacení nebo snížení úvěrů, aby jejich splácení rodinu finančně nezahltilo."],
      ["Budoucnost dětí", "Rezerva na jejich výchovu, studium a období, než se osamostatní."],
      ["Pomoc s péčí o domácnost", "Zajištění hlídání nebo jiné pomoci, pokud zemře rodič, který se o děti a domácnost převážně staral."],
    ],
    amountTitle: "Jak vysokou částku nastavit?",
    amountText: "Zohledníme vaše závazky, částku, která by rodině každý měsíc chyběla, a dobu, po kterou potřebuje podporu. Přihlédneme také k dostupným úsporám a stávajícímu pojištění. Porovnáme přitom vhodné varianty od více pojišťoven.",
    beneficiaryTitle: "Komu mají peníze připadnout?",
    beneficiaryText: "Ve smlouvě lze určit obmyšlenou osobu — člověka, kterému má v případě vaší smrti vzniknout právo na pojistné plnění. Společně projdeme, koho chcete zajistit, a nastavení průběžně přizpůsobíme změnám ve vaší rodině.",
    termsText: "Nárok na plnění a jeho výše se řídí sjednaným rozsahem a pojistnými podmínkami. Pojištění může poskytnout prostředky na doplacení závazků; samo o sobě neznamená automatické splacení všech dluhů.",
    source: "Vysvětlení pojmů · Slovník ČPP",
    meetingCta: "Probrat zajištění mých blízkých",
  },
  en: {
    kicker: "Life cover in the event of death",
    title: "Financial security for those left behind",
    close: "Close life cover details",
    detail: "Support for loved ones and financial commitments",
    intro: "Money cannot replace a loved one. It can help a family manage expenses and give them time to adjust to a new situation.",
    benefits: [
      ["A dignified farewell", "Funds for a funeral, a farewell ceremony and related one-off expenses."],
      ["Support for the family", "Money for housing, utilities, food and other everyday needs when an income is lost."],
      ["A mortgage and other commitments", "Funds to repay or reduce loans, helping prevent repayments from overwhelming the family financially."],
      ["Children’s future", "A reserve for their upbringing, education and the years before they become independent."],
      ["Help with care at home", "Childcare or other support if the parent who mainly looked after the children and household dies."],
    ],
    amountTitle: "How much cover should you arrange?",
    amountText: "We will consider your commitments, the monthly amount your family would be missing and how long they would need support. We will also take available savings and existing insurance into account. We will compare suitable options from several insurers.",
    beneficiaryTitle: "Who should receive the money?",
    beneficiaryText: "You can name a beneficiary in the policy — the person intended to become entitled to the insurance benefit if you die. We will discuss whom you want to support and review the arrangement as your family circumstances change.",
    termsText: "Entitlement and the benefit amount depend on the agreed cover and policy terms. Insurance can provide funds to repay commitments; it does not automatically settle every debt.",
    source: "Terminology · ČPP glossary (Czech)",
    meetingCta: "Discuss protection for my loved ones",
  },
  uk: {
    kicker: "Страхування на випадок смерті",
    title: "Фінансова підтримка для тих, хто залишиться",
    close: "Закрити опис страхування на випадок смерті",
    detail: "Захист близьких і фінансові зобов’язання",
    intro: "Гроші не замінять близьку людину. Проте вони можуть допомогти родині впоратися з витратами та дати час пристосуватися до нової ситуації.",
    benefits: [
      ["Гідне прощання", "Кошти на похорон, прощання та пов’язані з ними одноразові витрати."],
      ["Підтримка родини", "Гроші на житло, комунальні послуги, їжу та інші щоденні потреби після втрати доходу."],
      ["Іпотека та інші зобов’язання", "Кошти на погашення або зменшення кредитів, щоб платежі не стали непосильним фінансовим тягарем для родини."],
      ["Майбутнє дітей", "Резерв на виховання, навчання та період до їхньої самостійності."],
      ["Допомога з доглядом і побутом", "Догляд за дітьми або інша підтримка, якщо помирає хтось із батьків, хто переважно дбав про дітей і домашні справи."],
    ],
    amountTitle: "Яку страхову суму обрати?",
    amountText: "Врахуємо ваші зобов’язання, суму, якої родині бракуватиме щомісяця, та період необхідної підтримки. Також зважимо на доступні заощадження й наявне страхування. Порівняємо відповідні варіанти від кількох страховиків.",
    beneficiaryTitle: "Кому мають виплатити кошти?",
    beneficiaryText: "У договорі можна визначити вигодонабувача — людину, яка матиме право на страхову виплату в разі вашої смерті. Разом обговоримо, кого ви хочете забезпечити, і переглядатимемо налаштування відповідно до змін у вашій родині.",
    termsText: "Право на виплату та її розмір залежать від погодженого покриття й умов договору. Страхування може надати кошти для погашення зобов’язань, але саме по собі не означає автоматичного погашення всіх боргів.",
    source: "Пояснення термінів · Словник ČPP (чеською)",
    meetingCta: "Обговорити захист моїх близьких",
  },
} satisfies Record<OnlineCardLocale, unknown>;
