import type { OnlineCardLocale } from "@/lib/onlineCardI18n";

export const DISABILITY_SOURCES = {
  pension: "https://www.cssz.gov.cz/invalidni-duchod",
  degrees: "https://www.ipzs.gov.cz/invalidita-stupen-invalidity",
  causes: "https://www.cssz.gov.cz/documents/20143/3250926/Vypl%C3%A1cen%C3%A9%20invalidn%C3%AD%20d%C5%AFchody%20dle%20skupin%20diagn%C3%B3z.pdf/12093b00-cd4c-b594-7ac9-87f6ff2b4849",
};

export const DISABILITY_COPY = {
  cs: {
    title: "Invalidita", kicker: "Ochrana příjmu na delší dobu", close: "Zavřít detail invalidity", detail: "Stupně invalidity a dopad na rozpočet",
    badge: "Myslete na nemoc i úraz",
    intro: "Když zdraví omezí schopnost pracovat, rodinný rozpočet potřebuje oporu.",
    benefits: [
      ["Příjem může výrazně klesnout", "Státní invalidní důchod může pokrýt jen část toho, co jste dříve vydělávali v práci. Správně nastavené pojištění pomáhá tento finanční propad vyrovnat."],
      ["Splátky a rodina nepočkají", "Hypotéka, úvěry i běžné rodinné výdaje pokračují. Peníze z pojištění mohou pomoci se splácením a snížit riziko, že se dostanete do finančních potíží."],
      ["Mohou přibýt nové výdaje", "Invalidita může přinést i nečekané náklady. Pojistné plnění může pomoci s úpravou bydlení, nákupem pomůcek nebo další péčí."],
      ["Častěji nemoc než úraz", "U vyplácených invalidních důchodů převažují jako příčina nemoci. Mezi nejčastější patří onemocnění pohybového aparátu a duševní onemocnění. Proto je důležité řešit i krytí invalidity z nemoci."],
    ],
    causesSource: "ČSSZ · Příčiny invalidních důchodů k 31. 12. 2025",
    degreesTitle: "Tři stupně podle pracovní schopnosti", degreesIntro: "Pro účely státního důchodu se invalidita rozlišuje podle míry poklesu pracovní schopnosti:",
    degrees: ["I. stupeň", "II. stupeň", "III. stupeň"], capacityDrop: "pokles pracovní schopnosti", highestDegree: "70 % a více",
    degreesNote: "Tato procenta neudávají pokles mzdy ani výši pojistného plnění. Zdravotní stav posuzuje IPZS; samotný název diagnózy stupeň invalidity neurčuje.",
    supportTitle: "Státní důchod a vaše pojištění",
    stateTitle: "Invalidní důchod od státu", stateText: "Uznání invalidity samo o sobě neznamená nárok na důchod. Obvykle je potřeba i dostatečná doba důchodového pojištění; zákon stanoví výjimky. Částku ČSSZ určuje individuálně podle stupně invalidity, dob pojištění a výdělků.",
    insuranceTitle: "Plnění z vlastní smlouvy", insuranceText: "Podle sjednané varianty může pojišťovna vyplatit jednorázovou částku nebo pravidelnou rentu. Rozhoduje rozsah krytí, sjednané částky a podmínky konkrétní smlouvy. Peníze mohou pomoci s běžnými výdaji, úpravou bydlení nebo závazky.",
    recommendationTitle: "Co při nastavení hlídám", recommendationText: "Projdeme krytí nemoci i úrazu a všech tří stupňů invalidity. Výši ochrany nastavíme podle vašich výdajů, závazků, rezerv a doby, po kterou na příjmu závisíte. Důležité je i to, zda pojistná částka v čase klesá.",
    budgetTitle: "Kolik by vám v rozpočtu chybělo?", budgetIntro: "Zkuste si změnit modelové částky. Zbývající příjem zadáváte sami — například důchod a reálný výdělek po změně zdravotního stavu. Tento model výši státního důchodu nepočítá.",
    expenses: "Měsíční výdaje (Kč)", expensesHint: "Bydlení, splátky a běžné potřeby.", income: "Zbývající měsíční příjem (Kč)", incomeHint: "Příjem po změně zdravotního stavu, který očekáváte.", horizon: "Na jak dlouho počítat", years: ["1 rok", "5 let", "10 let", "20 let"],
    monthlyGap: "Chybělo by měsíčně", totalGap: "Za celé zvolené období", covered: "Výdaje pokryté příjmem", uncovered: "Chybějící část", calculation: "Měsíční rozdíl × 12 × počet let",
    budgetNote: "Jde o prostý součet výpadku při stálých částkách, bez inflace, zhodnocení či čerpání rezerv. Nezahrnuje další jednorázové náklady. Není to výpočet důchodu, pojistného plnění ani automatické doporučení pojistné částky.",
    noGap: "Při těchto částkách je měsíční rozpočet pokrytý. Ještě je vhodné zohlednit rezervy a případné nové výdaje.", invalidAmount: "Vyplňte obě částky celými čísly od 0 do 1 000 000 Kč.",
    faqTitle: "Na co se často ptáte", faqs: [
      ["Mohu při invalidním důchodu pracovat?", "Ano, podle svého zdravotního stavu můžete využít zbývající pracovní schopnost. Samotný výdělek nárok na státní invalidní důchod automaticky neruší. Konkrétní pracovní možnosti jsou individuální."],
      ["Je invalidita totéž co neschopenka nebo trvalé následky úrazu?", "Každé krytí řeší jinou situaci. Neschopenka se týká dočasné pracovní neschopnosti, invalidita dlouhodobého poklesu pracovní schopnosti. Trvalé následky úrazu se hodnotí podle následků poranění a pojistných tabulek. Jedno krytí automaticky nenahrazuje druhé."],
      ["Co ověřit v konkrétní smlouvě?", "Které stupně a příčiny invalidity jsou pojištěné, výluky, případnou čekací dobu a konec krytí. Také zda pro plnění stačí uznání invalidity, jaké doklady pojišťovna vyžaduje a co se stane při přechodu do vyššího stupně."],
    ],
    pensionSource: "ČSSZ · Invalidní důchod", degreesSource: "IPZS · Stupně invalidity", meetingCta: "Probrat ochranu při invaliditě",
  },
  en: {
    title: "Disability", kicker: "Long-term income protection", close: "Close disability details", detail: "Disability degrees and your budget",
    badge: "Consider both illness and injury",
    intro: "When your health limits your ability to work, your family budget needs support.",
    benefits: [
      ["Your income may fall substantially", "A state disability pension may cover only part of what you previously earned at work. Appropriately arranged insurance can help bridge that financial gap."],
      ["Repayments and family expenses continue", "Mortgage payments, loans and everyday family expenses do not stop. Insurance benefits can help with repayments and reduce the risk of financial difficulties."],
      ["New expenses may arise", "Disability can also bring unexpected costs. Insurance benefits can help with home adaptations, assistive equipment or additional care."],
      ["Illness is more common than injury", "Illnesses account for most disability pensions being paid. Musculoskeletal conditions and mental health conditions are among the most common causes. Cover for disability caused by illness therefore matters too."],
    ],
    causesSource: "ČSSZ · Disability pension causes as of 31 Dec 2025",
    degreesTitle: "Three degrees of reduced work capacity", degreesIntro: "For Czech state pension purposes, disability is classified by the reduction in work capacity:",
    degrees: ["1st degree", "2nd degree", "3rd degree"], capacityDrop: "reduction in work capacity", highestDegree: "70% or more",
    degreesNote: "These percentages do not represent a drop in salary or the amount of an insurance benefit. IPZS assesses your health; a diagnosis alone does not determine the disability degree.",
    supportTitle: "The state pension and your insurance",
    stateTitle: "State disability pension", stateText: "Recognised disability does not automatically entitle you to a pension. A sufficient pension insurance record is usually required, with statutory exceptions. ČSSZ calculates each pension using the disability degree, insurance periods and earnings.",
    insuranceTitle: "Benefits from your own policy", insuranceText: "Depending on the selected cover, an insurer may pay a lump sum or a regular income. The scope of cover, insured amounts and your policy terms determine entitlement. The benefit can help with everyday expenses, home adaptations or financial commitments.",
    recommendationTitle: "What I focus on when arranging cover", recommendationText: "We will review cover for illness, injury and all three disability degrees. The amount will reflect your expenses, commitments, savings and how long you depend on your income. It also matters whether the insured amount decreases over time.",
    budgetTitle: "What would your budget be missing?", budgetIntro: "Try changing the example amounts. You enter the remaining income yourself, such as a pension and realistic earnings after a change in health. This model does not calculate your state pension.",
    expenses: "Monthly expenses (CZK)", expensesHint: "Housing, loan repayments and everyday needs.", income: "Remaining monthly income (CZK)", incomeHint: "Income you expect after a change in health.", horizon: "Period to consider", years: ["1 year", "5 years", "10 years", "20 years"],
    monthlyGap: "Monthly shortfall", totalGap: "Over the selected period", covered: "Expenses covered by income", uncovered: "Shortfall", calculation: "Monthly shortfall × 12 × years",
    budgetNote: "A simple total assuming constant amounts, without inflation, investment returns or use of savings. Additional one-off costs are excluded. This is not a pension or insurance benefit calculation, or an automatic recommendation for your insured amount.",
    noGap: "These amounts cover your monthly budget. Savings and potential new expenses still need to be considered.", invalidAmount: "Enter both amounts as whole numbers from CZK 0 to 1,000,000.",
    faqTitle: "Common questions", faqs: [
      ["Can I work while receiving a disability pension?", "Yes, you can use your remaining work capacity according to your health. Earning money does not automatically end entitlement to a Czech state disability pension. Your ability to work depends on your individual situation."],
      ["Is disability the same as sick leave or permanent injury?", "Each type of cover addresses a different situation. Sick leave concerns temporary incapacity for work; disability concerns a long-term reduction in work capacity. Permanent accident consequences are assessed using the injury and the insurer’s tables. One type of cover does not automatically replace another."],
      ["What should I check in my policy?", "The covered disability degrees and causes, exclusions, any waiting period and the end of cover. Also check whether recognised disability is sufficient for payment, which documents the insurer requires and how a move to a higher degree affects benefits."],
    ],
    pensionSource: "ČSSZ · Disability pension", degreesSource: "IPZS · Disability degrees", meetingCta: "Discuss disability cover",
  },
  uk: {
    title: "Інвалідність", kicker: "Довгостроковий захист доходу", close: "Закрити опис страхування інвалідності", detail: "Ступені інвалідності та ваш бюджет",
    badge: "Враховуйте і хворобу, і травму",
    intro: "Коли здоров’я обмежує здатність працювати, сімейному бюджету потрібна підтримка.",
    benefits: [
      ["Дохід може суттєво зменшитися", "Державна пенсія з інвалідності може покрити лише частину вашого попереднього заробітку. Належно підібране страхування допомагає компенсувати цей фінансовий розрив."],
      ["Платежі та сімейні витрати тривають", "Іпотека, кредити й повсякденні сімейні витрати не зникають. Страхова виплата може допомогти з платежами та знизити ризик фінансових труднощів."],
      ["Можуть виникнути нові витрати", "Інвалідність може спричинити й неочікувані витрати. Страхові кошти можуть допомогти з пристосуванням житла, придбанням допоміжних засобів або додатковим доглядом."],
      ["Хвороби частіші за травми", "Серед причин інвалідності, за якою виплачуються пенсії, переважають хвороби. До найпоширеніших належать захворювання опорно-рухового апарату та психічні розлади. Тому важливе й покриття інвалідності через хворобу."],
    ],
    causesSource: "ČSSZ · Причини пенсій з інвалідності на 31.12.2025",
    degreesTitle: "Три ступені за зниженням працездатності", degreesIntro: "Для державної пенсії в Чехії інвалідність розрізняють за ступенем зниження працездатності:",
    degrees: ["I ступінь", "II ступінь", "III ступінь"], capacityDrop: "зниження працездатності", highestDegree: "70 % і більше",
    degreesNote: "Ці відсотки не означають зниження зарплати чи розмір страхової виплати. Стан здоров’я оцінює IPZS; сама назва діагнозу не визначає ступінь інвалідності.",
    supportTitle: "Державна пенсія та ваше страхування",
    stateTitle: "Державна пенсія з інвалідності", stateText: "Визнання інвалідності не дає автоматичного права на пенсію. Зазвичай потрібен і достатній страховий стаж; закон передбачає винятки. ČSSZ визначає суму індивідуально за ступенем інвалідності, страховим стажем і заробітком.",
    insuranceTitle: "Виплата за вашим договором", insuranceText: "Залежно від обраного покриття страховик може виплатити одноразову суму або регулярну ренту. Право на виплату визначають покриття, страхові суми й умови договору. Кошти можуть допомогти з поточними витратами, пристосуванням житла чи зобов’язаннями.",
    recommendationTitle: "На що я звертаю увагу", recommendationText: "Перевіримо покриття хвороб, травм і всіх трьох ступенів інвалідності. Суму захисту визначимо з огляду на ваші витрати, зобов’язання, заощадження та період залежності від доходу. Важливо також, чи зменшується страхова сума з часом.",
    budgetTitle: "Скільки бракувало б у бюджеті?", budgetIntro: "Спробуйте змінити умовні суми. Залишковий дохід ви вводите самі — наприклад, пенсію та реалістичний заробіток після зміни стану здоров’я. Ця модель не розраховує державну пенсію.",
    expenses: "Місячні витрати (Kč)", expensesHint: "Житло, платежі за кредитами та повсякденні потреби.", income: "Залишковий місячний дохід (Kč)", incomeHint: "Дохід, який ви очікуєте після зміни стану здоров’я.", horizon: "Період розрахунку", years: ["1 рік", "5 років", "10 років", "20 років"],
    monthlyGap: "Бракувало б щомісяця", totalGap: "За весь обраний період", covered: "Витрати, покриті доходом", uncovered: "Нестача коштів", calculation: "Місячна нестача × 12 × кількість років",
    budgetNote: "Проста сума нестачі за незмінних сум, без інфляції, інвестиційного доходу чи використання заощаджень. Додаткові одноразові витрати не враховано. Це не розрахунок пенсії, страхової виплати чи автоматична рекомендація страхової суми.",
    noGap: "За цих сум місячний бюджет покрито. Ще варто врахувати заощадження та можливі нові витрати.", invalidAmount: "Введіть обидві суми цілими числами від 0 до 1 000 000 Kč.",
    faqTitle: "Поширені запитання", faqs: [
      ["Чи можу я працювати, отримуючи пенсію з інвалідності?", "Так, відповідно до свого стану здоров’я ви можете використовувати залишкову працездатність. Сам заробіток автоматично не скасовує права на чеську державну пенсію з інвалідності. Можливість працювати залежить від індивідуальної ситуації."],
      ["Чи інвалідність означає те саме, що лікарняний або постійні наслідки травми?", "Кожне покриття стосується іншої ситуації. Лікарняний — тимчасової непрацездатності, інвалідність — довгострокового зниження працездатності. Постійні наслідки травми оцінюють за ушкодженням і таблицями страховика. Одне покриття автоматично не замінює інше."],
      ["Що перевірити у своєму договорі?", "Які ступені та причини інвалідності покрито, винятки, можливий період очікування й закінчення покриття. Також чи достатньо визнання інвалідності для виплати, які документи потрібні та що відбувається при переході до вищого ступеня."],
    ],
    pensionSource: "ČSSZ · Пенсія з інвалідності", degreesSource: "IPZS · Ступені інвалідності", meetingCta: "Обговорити захист у разі інвалідності",
  },
} satisfies Record<OnlineCardLocale, unknown>;
