import type { OnlineCardLocale } from "@/lib/onlineCardI18n";

export const HOSPITALISATION_SOURCES = {
  flexi: "https://www.koop.cz/file/edee/dokumenty/pojisteni-osob/rizikove-zivotni-pojisteni-flexi/PP_RZP_Flexi.pdf#page=50",
  spa: "https://www.generaliceska.cz/urazove-pojisteni-pro-seniory",
  accompaniment: "https://www.cpp.cz/zivotni-a-urazove-pojisteni/neon",
};

export const HOSPITALISATION_COPY = {
  cs: {
    title: "Hospitalizace", kicker: "Finanční pomoc během léčby",
    close: "Zavřít detail hospitalizace", detail: "Denní dávka, progrese a doléčení",
    intro: "Při pobytu v nemocnici mohou přibýt výdaje za dopravu blízkých, hlídání dětí nebo pomoc doma. Pojištění hospitalizace může přinést peníze, které využijete podle svých potřeb.",
    dailyTitle: "Peníze za uznané dny pobytu",
    dailyText: "Základem je sjednaná denní dávka a počet dnů, které pojišťovna uzná. Ověříme, zda smlouva kryje nemoc i úraz, nebo pouze úraz, a jak dlouhý pobyt je nutný pro vznik nároku.",
    example: "Příklad bez progrese: 500 Kč denně × 10 uznaných dnů",
    exampleNote: "Model při splnění podmínek smlouvy. Počet uznaných dnů se řídí pravidly konkrétního pojištění.",
    progressionTitle: "Progresivní plnění",
    progressionText: "U některých produktů se denní plnění s délkou pobytu zvyšuje. Podmínky určují, zda se různé násobky počítají jen pro jednotlivá pásma dnů, nebo jiným způsobem. Vyšší sazba nemusí platit zpětně pro celý pobyt.",
    spaTitle: "Lázně a rehabilitační pobyt",
    spaText: "Vybraná pojištění zahrnují i léčebné lázeňské nebo rehabilitační pobyty. Podmínkou může být doporučení lékaře, návaznost na hospitalizaci a omezený počet dnů. Samoplátecký wellness pobyt ani ambulantní rehabilitace nejsou automaticky kryté.",
    accompanimentTitle: "Když v nemocnici zůstává dítě",
    accompanimentText: "Některé produkty nabízejí připojištění doprovodu nebo vyšší plnění při pobytu dítěte s doprovázející osobou. Ověříme, koho je potřeba pojistit a jak se společný pobyt dokládá.",
    checkTitle: "Co spolu ověříme ve smlouvě",
    checks: [
      ["Začátek a délku krytí", "Čekací dobu, minimální délku pobytu, započítávání dnů a případný limit plnění."],
      ["Rozsah a doklady", "Výluky, podmínky doléčení a potřebné lékařské zprávy, zejména propouštěcí zprávu."],
    ],
    recoveryTitle: "Návratem z nemocnice léčba často nekončí",
    recoveryText: "Hospitalizace a pracovní neschopnost mají odlišné podmínky. Společně sladíme krytí pobytu v nemocnici i případného výpadku příjmu během léčby doma. Porovnáme přitom vhodné varianty od více pojišťoven.",
    flexiSource: "Příklad podmínek · Kooperativa FLEXI",
    spaSource: "Příklad krytí lázní · Generali Česká, úrazové pojištění seniorů",
    accompanimentSource: "Příklad krytí doprovodu · ČPP NEON",
    meetingCta: "Probrat pojištění hospitalizace",
  },
  en: {
    title: "Hospitalisation", kicker: "Financial help during treatment",
    close: "Close hospitalisation details", detail: "Daily benefits, progression and recovery",
    intro: "A hospital stay can bring extra costs for family travel, childcare or help at home. Hospitalisation cover can provide money to use according to your needs.",
    dailyTitle: "Money for eligible days in hospital",
    dailyText: "The starting point is your insured daily amount and the number of days recognised by the insurer. We will check whether the policy covers illness and injury or injury only, and the minimum stay required.",
    example: "Example without progression: CZK 500 a day × 10 eligible days",
    exampleNote: "Illustrative calculation assuming the policy conditions are met. Eligible days are counted under the specific policy rules.",
    progressionTitle: "Progressive benefits",
    progressionText: "Some products increase daily benefits for longer stays. Their terms determine whether different multipliers apply to individual bands of days or use another calculation. A higher rate does not necessarily apply retrospectively to the whole stay.",
    spaTitle: "Spa treatment and rehabilitation stays",
    spaText: "Selected policies also cover therapeutic spa or rehabilitation stays. Conditions may include a doctor’s recommendation, a preceding hospital stay and a limited number of days. Self-funded wellness breaks and outpatient rehabilitation are not automatically covered.",
    accompanimentTitle: "When a child stays in hospital",
    accompanimentText: "Some products offer cover for an accompanying person or a higher benefit when a child is accompanied. We will check who needs to be insured and how to document the shared stay.",
    checkTitle: "What we will check in your policy",
    checks: [
      ["When and for how long cover applies", "Waiting periods, the minimum stay, how days are counted and any benefit limit."],
      ["Scope and documents", "Exclusions, conditions for follow-up treatment and required medical records, particularly the discharge report."],
    ],
    recoveryTitle: "Treatment often continues after discharge",
    recoveryText: "Hospitalisation and incapacity-for-work cover have different conditions. We will coordinate cover for hospital stays with protection against lost income during recovery at home. We will compare suitable options from several insurers.",
    flexiSource: "Example terms · Kooperativa FLEXI (Czech)",
    spaSource: "Example spa cover · Generali Česká senior accident insurance (Czech)",
    accompanimentSource: "Example accompanying-person cover · ČPP NEON (Czech)",
    meetingCta: "Discuss hospitalisation cover",
  },
  uk: {
    title: "Госпіталізація", kicker: "Фінансова допомога під час лікування",
    close: "Закрити опис госпіталізації", detail: "Денні виплати, прогресія та долікування",
    intro: "Перебування в лікарні може спричинити додаткові витрати на поїздки близьких, догляд за дітьми чи допомогу вдома. Страхування госпіталізації може надати кошти, які ви використаєте відповідно до своїх потреб.",
    dailyTitle: "Кошти за визнані дні перебування",
    dailyText: "Основою є погоджена денна сума та кількість днів, визнаних страховиком. Перевіримо, чи охоплює договір хвороби й травми або лише травми, та яка мінімальна тривалість перебування потрібна для виплати.",
    example: "Приклад без прогресії: 500 Kč на день × 10 визнаних днів",
    exampleNote: "Умовний розрахунок за виконання умов договору. Кількість визнаних днів визначається правилами конкретного страхування.",
    progressionTitle: "Прогресивні виплати",
    progressionText: "У деяких продуктах денна виплата зростає зі збільшенням тривалості перебування. Умови визначають, чи застосовуються множники лише до окремих діапазонів днів, чи використовується інший розрахунок. Вища ставка не обов’язково діє заднім числом на весь період.",
    spaTitle: "Санаторне лікування та реабілітація",
    spaText: "Окремі договори охоплюють також лікувальні санаторні або реабілітаційні перебування. Умовами можуть бути рекомендація лікаря, зв’язок із попередньою госпіталізацією та обмежена кількість днів. Самостійно оплачений оздоровчий відпочинок і амбулаторна реабілітація не покриваються автоматично.",
    accompanimentTitle: "Коли дитина перебуває в лікарні",
    accompanimentText: "Деякі продукти пропонують страхування супроводу або підвищену виплату, коли дитина перебуває в лікарні із супроводжуючою особою. Перевіримо, кого потрібно застрахувати та як підтвердити спільне перебування.",
    checkTitle: "Що перевіримо у вашому договорі",
    checks: [
      ["Початок і тривалість покриття", "Період очікування, мінімальну тривалість перебування, підрахунок днів і можливий ліміт виплат."],
      ["Обсяг і документи", "Винятки, умови долікування та необхідні медичні документи, зокрема виписку з лікарні."],
    ],
    recoveryTitle: "Лікування часто триває й після виписки",
    recoveryText: "Страхування госпіталізації та тимчасової непрацездатності мають різні умови. Разом узгодимо покриття перебування в лікарні й можливого зменшення доходу під час лікування вдома. Порівняємо відповідні варіанти від кількох страховиків.",
    flexiSource: "Приклад умов · Kooperativa FLEXI (чеською)",
    spaSource: "Приклад покриття санаторію · Generali Česká, страхування від травм для літніх людей (чеською)",
    accompanimentSource: "Приклад покриття супроводу · ČPP NEON (чеською)",
    meetingCta: "Обговорити страхування госпіталізації",
  },
} satisfies Record<OnlineCardLocale, unknown>;
