import type { OnlineCardLocale } from "@/lib/onlineCardI18n";

export const SERIOUS_ILLNESS_SOURCES = {
  definitions: "https://www.cpp.cz/file/edee/dokumenty/zivotni-rizikove-a-urazove-pojisteni/brozury-pojistnych-podminek/pojisteni-neon/neon-risk/brozura-neon-risk_01_2026.pdf#page=42",
  benefits: "https://www.koop.cz/file/edee/dokumenty/pojisteni-osob/zivotni-pojisteni-flexi/A2_PP_Zivotni_pojisteni_FLEXI_01_2025_v3_OPTIMALIZACE.PDF#page=10",
};

export const SERIOUS_ILLNESS_COPY = {
  cs: {
    title: "Závažná onemocnění a poranění", kicker: "Finanční prostor pro léčbu a zotavení",
    close: "Zavřít detail závažných onemocnění a poranění", detail: "Kryté diagnózy a podpora během léčby",
    intro: "Vážná diagnóza může změnit každodenní život celé rodiny. Peníze z pojištění mohou pomoci zvládnout nové výdaje a dát vám více prostoru soustředit se na léčbu.",
    warningTitle: "Pozor na přesný seznam diagnóz",
    warningText: "Pojištění se vztahuje pouze na diagnózy uvedené v pojistných podmínkách sjednané varianty.",
    warningDetail: "Musí být splněna i jejich definice, například požadovaný rozsah nebo stadium. Samotná závažnost nemoci či poranění automaticky neznamená nárok na plnění.",
    definitionsSource: "Příklad definic · ČPP NEON RISK",
    reasonsTitle: "S čím mohou peníze pomoci",
    reasons: [
      ["Domácnost běží dál", "Nájem, splátky, energie i běžné nákupy je potřeba řešit také v době, kdy omezíte práci."],
      ["Blízcí mohou být nablízku", "Rezerva na hlídání dětí, pomoc doma nebo období, kdy partner omezí práci, aby o vás pečoval."],
      ["Výdaje kolem léčby", "Doprava na vyšetření, ubytování blízkých nebo vlastní výdaje spojené se zotavováním."],
      ["Více prostoru na zotavení", "Finanční podpora může zmírnit tlak na rychlý návrat do práce a pomoci šetřit rodinné úspory."],
    ],
    paymentTitle: "Jaké plnění můžete dostat",
    paymentText: "Podle diagnózy a podmínek může pojišťovna vyplatit sjednanou částku nebo její část. U některých variant lze plnit opakovaně, ale jen podle pravidel daného produktu.",
    paymentSource: "Příklad pravidel plnění · Kooperativa FLEXI",
    checksTitle: "Co spolu ověříme ve smlouvě",
    checks: [
      ["Seznam a definice", "Které diagnózy a stupně závažnosti skutečně zahrnuje vaše varianta."],
      ["Podmínky nároku", "Čekací doby, výluky, potřebné lékařské podklady a další podmínky výplaty."],
    ],
    amountTitle: "Částku nastavíme podle vašeho života",
    amountText: "Vyjdeme z výdajů domácnosti, možného výpadku příjmu a doby, na kterou chcete mít rezervu. Zohledníme úspory i ostatní pojištění a sladíme krytí s invaliditou a pracovní neschopností. Porovnáme přitom vhodné varianty od více pojišťoven.",
    sourcesNote: "Odkazy ukazují příklady podmínek konkrétních produktů. Pro vaši smlouvu je rozhodující její sjednaná varianta a verze podmínek.",
    meetingCta: "Probrat krytí závažných onemocnění",
  },
  en: {
    title: "Serious illnesses and injuries", kicker: "Financial breathing room for recovery",
    close: "Close serious illness and injury details", detail: "Covered diagnoses and support during treatment",
    intro: "A serious diagnosis can change daily life for the whole family. Insurance benefits can help with new expenses and give you more room to focus on treatment.",
    warningTitle: "Check the exact list of diagnoses",
    warningText: "Cover applies only to diagnoses listed in the policy terms for your chosen option.",
    warningDetail: "Their definitions must also be met, including any required severity or stage. An illness or injury being serious does not automatically qualify it for a benefit.",
    definitionsSource: "Example definitions · ČPP NEON RISK (Czech)",
    reasonsTitle: "What the money could help with",
    reasons: [
      ["Household bills continue", "Rent, loan payments, energy bills and everyday shopping still need to be covered when you work less."],
      ["Support from loved ones", "A reserve for childcare, help at home or a period when your partner reduces their working hours to care for you."],
      ["Costs around treatment", "Travel to appointments, accommodation for family or personal expenses during recovery."],
      ["More room to recover", "Financial support can ease the pressure to return to work quickly and help preserve family savings."],
    ],
    paymentTitle: "What benefit could you receive?",
    paymentText: "Depending on the diagnosis and policy terms, the insurer may pay the insured amount or part of it. Some options allow further claims, subject to the product’s rules.",
    paymentSource: "Example benefit rules · Kooperativa FLEXI (Czech)",
    checksTitle: "What we will check in your policy",
    checks: [
      ["List and definitions", "Which diagnoses and levels of severity your option actually includes."],
      ["Conditions for a claim", "Waiting periods, exclusions, medical evidence and other payment requirements."],
    ],
    amountTitle: "We will tailor the amount to your life",
    amountText: "We will consider household expenses, potential lost income and how long you want a reserve to last. We will account for savings and existing insurance, coordinating this cover with disability and incapacity-for-work insurance. We will compare suitable options from several insurers.",
    sourcesNote: "The links show examples of terms for specific products. Your chosen option and the terms applicable to your policy determine your cover.",
    meetingCta: "Discuss serious illness cover",
  },
  uk: {
    title: "Тяжкі захворювання та травми", kicker: "Фінансова підтримка для лікування й відновлення",
    close: "Закрити опис страхування тяжких захворювань і травм", detail: "Покриті діагнози та підтримка під час лікування",
    intro: "Тяжкий діагноз може змінити повсякденне життя всієї родини. Страхова виплата може допомогти з новими витратами та дати вам більше можливостей зосередитися на лікуванні.",
    warningTitle: "Зверніть увагу на точний перелік діагнозів",
    warningText: "Страхування поширюється лише на діагнози, зазначені в умовах обраного варіанта страхування.",
    warningDetail: "Також мають бути виконані їхні визначення, зокрема вимоги до тяжкості або стадії. Сама тяжкість захворювання чи травми не означає автоматичного права на виплату.",
    definitionsSource: "Приклад визначень · ČPP NEON RISK (чеською)",
    reasonsTitle: "У чому можуть допомогти кошти",
    reasons: [
      ["Побутові витрати залишаються", "Оренду, кредити, комунальні послуги та повсякденні покупки потрібно оплачувати й тоді, коли ви працюєте менше."],
      ["Близькі можуть бути поруч", "Резерв на догляд за дітьми, допомогу вдома або період, коли партнер менше працює, щоб доглядати за вами."],
      ["Витрати, пов’язані з лікуванням", "Поїздки на обстеження, проживання близьких або власні витрати під час відновлення."],
      ["Більше можливостей для відновлення", "Фінансова підтримка може зменшити тиск щодо швидкого повернення до роботи та допомогти зберегти сімейні заощадження."],
    ],
    paymentTitle: "Яку виплату можна отримати",
    paymentText: "Залежно від діагнозу та умов страховик може виплатити страхову суму або її частину. Деякі варіанти допускають повторні виплати, але лише за правилами конкретного продукту.",
    paymentSource: "Приклад правил виплат · Kooperativa FLEXI (чеською)",
    checksTitle: "Що перевіримо у вашому договорі",
    checks: [
      ["Перелік і визначення", "Які діагнози та ступені тяжкості насправді охоплює ваш варіант."],
      ["Умови отримання виплати", "Періоди очікування, виключення, медичні документи та інші вимоги до виплати."],
    ],
    amountTitle: "Підберемо суму відповідно до вашого життя",
    amountText: "Врахуємо витрати родини, можливу втрату доходу та бажаний строк фінансового резерву. Зважимо на заощадження й чинні поліси та узгодимо покриття зі страхуванням інвалідності й тимчасової непрацездатності. Порівняємо відповідні варіанти від кількох страховиків.",
    sourcesNote: "Посилання містять приклади умов конкретних продуктів. Для вашого договору визначальними є обраний варіант і чинна для нього версія умов.",
    meetingCta: "Обговорити страхування тяжких захворювань",
  },
} satisfies Record<OnlineCardLocale, unknown>;
