export const SICK_LEAVE_COPY = {
  cs: {
    title: "Pracovní neschopnost", kicker: "Ochrana vašeho příjmu", close: "Zavřít detail pracovní neschopnosti",
    tabs: "Obsah detailu", overview: "Jak pojištění funguje", calculator: "Spočítat příjem", detail: "Více o krytí a výpočet příjmu",
    badge: "Velmi doporučené při závislosti na příjmu",
    intro: "Pokud jsou vaše výdaje závislé na pravidelném příjmu, patří pracovní neschopnost mezi připojištění, která velmi doporučuji. Sjednaná denní dávka pomáhá dorovnat výpadek příjmu při kratší i dlouhodobé pracovní neschopnosti.",
    coverage: "Krytí lze sjednat pro nemoc i úraz. Ověříme, že smlouva zahrnuje obě příčiny a odpovídá vaší práci i zdravotnímu stavu. Samotná neschopenka neznamená automaticky nárok na plnění z každé smlouvy.",
    startTitle: "Od kdy pojišťovna plní?", starts: ["Od 15. dne", "Od 29. dne", "Od 60. dne"],
    startText: "Běžně se setkáte s těmito variantami. Karenční doba určuje, jak dlouho musí neschopnost trvat a od kterého dne lze plnit. Přesná délka i dostupnost zpětného plnění závisí na produktu.",
    retroTitle: "Zpětně od 1. dne", retroText: "Jakmile neschopnost dosáhne sjednané minimální délky, pojišťovna při splnění podmínek zaplatí i předchozí dny od jejího počátku. Kratší neschopnost se z této varianty neproplatí.",
    followingTitle: "Následně od sjednaného dne", followingText: "Plnění se počítá až od zvoleného dne. Předchozí dny neschopnosti zůstávají bez plnění z tohoto připojištění.",
    exampleTitle: "Stejná neschopnost. Jiný počet placených dní.", exampleText: "Model: 30 dní neschopnosti, denní dávka 500 Kč, varianta od 15. dne. Předpokládáme splnění podmínek smlouvy.",
    retroExample: "Zpětně: 30 × 500 Kč", followingExample: "Následně: 16 × 500 Kč", exampleNote: "Zpětně neznamená, že peníze přijdou hned první den. Jde o dny, za které vznikne nárok na plnění.",
    recommendationTitle: "Jaké nastavení obvykle doporučuji",
    recommendation: "Pokud jste závislí na příjmu a nemáte velkou rezervu, obecně doporučuji zvážit variantu od 15. dne se zpětným plněním od 1. dne, pokud ji produkt nabízí pro nemoc i úraz.",
    price: "Pokud je cenový rozdíl malý, širší ochrana může stát za to. Konkrétní cenu vždy porovnáme — závisí na produktu, věku, povolání i zdravotním stavu. Vyšší rezerva může umožnit delší karenční dobu.",
    checksTitle: "Co spolu ještě zkontrolujeme",
    checks: [
      ["Čekací dobu od sjednání", "Čekací doba běží od začátku pojištění; karenční doba se týká konkrétní neschopnosti. U nemoci, úrazu či těhotenství se pravidla mohou lišit."],
      ["Výši dávky a doložení příjmu", "Denní částku nastavíme podle skutečného výpadku příjmu, výdajů a rezerv. Ověříme také limity a doklady, které bude pojišťovna požadovat."],
      ["Výluky a délku plnění", "Prověříme předchozí onemocnění, případná omezení u zad, psychických potíží či těhotenství a maximální dobu plnění. Dlouhodobou ochranu doplňuje pojištění invalidity."],
      ["Pravidla pro OSVČ", "Běžné zálohy na sociální pojištění nejsou dobrovolné nemocenské pojištění. Zkontrolujeme nárok na státní dávku i podmínky soukromého pojištění pro vaši činnost."],
    ],
    calculateCta: "Spočítat, kolik dostanu", meetingCta: "Probrat nastavení pojištění",
    calcTitle: "Kolik dostanete během neschopnosti?", calcIntro: "Orientační výpočet pro rok 2026. Odděluje náhradu od zaměstnavatele a nemocenské od OSSZ.",
    employment: "Pracovní situace", employee: "Zaměstnanec", selfEmployed: "OSVČ", period: "Délka pracovní neschopnosti", days: "dní",
    gross: "Průměrný hrubý příjem měsíčně", grossHint: "Započitatelný příjem za posledních 12 měsíců, v Kč.",
    net: "Běžný čistý měsíční příjem", netHint: "Nepovinné. Pro porovnání s tím, co vám běžně zůstává na výdaje. U OSVČ po nákladech, daních a odvodech.",
    insured: "Platím si dobrovolné nemocenské pojištění a splňuji podmínky nároku.",
    insuredHint: "U OSVČ se zpravidla vyžadují alespoň 3 měsíce účasti před vznikem neschopnosti a během ní nesmíte osobně vykonávat svou činnost. Existují zákonné výjimky.",
    uninsured: "Bez nároku na nemocenské z dobrovolného pojištění počítáme u OSVČ s 0 Kč od OSSZ. Zaměstnavatel OSVČ nic nehradí.",
    base: "Průměrný měsíční základ nemocenského pojištění", baseHint: "V Kč. Nejde o obrat, zisk ani měsíční platbu pojistného. Základ zjistíte u ČSSZ.",
    precision: "Zpřesnit náhradu od zaměstnavatele", hourly: "Průměrný hodinový výdělek", hourlyHint: "Nepovinné, v Kč/h. PHV pro náhrady z výplatní pásky nebo mzdové účtárny za předchozí čtvrtletí.",
    workingDays: "Placené pracovní dny v prvních 14 dnech", workingDaysHint: "0–14 dní podle rozvrhu, včetně svátků s náhradou.", hours: "Hodin za pracovní den", hoursHint: "Nejvýše 24 h; u různých směn jejich průměr.",
    estimatedHint: "Bez hodinového výdělku používáme hrubou mzdu ÷ 173,33 h (model 40 h týdně). Výchozí rozvrh je 10 dní po 8 h v prvních 14 dnech. U kratšího úvazku či směn údaje zpřesněte.",
    invalid: "Zadejte platnou nezápornou částku. Příjmy a hodinový výdělek musí být větší než 0; rozvrh musí odpovídat uvedeným mezím.",
    empty: "Doplňte příjem, aby se zobrazil orientační výpočet.", example: "Vyzkoušet modelový příklad",
    employer: "Zaměstnavatel", noEmployer: "OSVČ nemá náhradu od zaměstnavatele.", employerNote: "Náhrada za rozvržené hodiny v 1.–14. dni.", state: "OSSZ", stateNote: "Nemocenské za kalendářní dny od 15. dne.", total: "Celkem za celé období", totalNote: "Součet za vybraný počet dní, nikoli měsíční dávka. Bez soukromého pojištění.",
    normalIncome: "Běžný čistý příjem za stejné období", gap: "Orientační výpadek příjmu", noGap: "V tomto modelu nevychází kladný rozdíl oproti zadanému čistému příjmu.", addNet: "Doplňte čistý příjem a uvidíte, kolik by vám za toto období chybělo.",
    breakdown: "Jak se částka skládá", periods: ["15.–30. den", "31.–60. den", "61.–90. den"], daily: "Kč / den", reduced: "z redukovaného denního základu",
    assumptions: "Model používá měsíční základ × 12 / 365 bez vyloučených dní. Předpokládá trvající běžný nárok; nezohledňuje zvláštní situace, např. souběh s důchodem. Čistý příjem porovnává po 30denních měsících. Skutečná částka závisí na podkladech zaměstnavatele a ČSSZ.",
    sources: "Pravidla a zdroje", privateSource: "Příklad variant krytí · ČPP", privacy: "Zadané částky se používají jen pro výpočet v tomto okně.",
  },
  en: {
    title: "Incapacity for work", kicker: "Protecting your income", close: "Close sick leave details",
    tabs: "Detail content", overview: "How the cover works", calculator: "Calculate income", detail: "Cover details and income calculator",
    badge: "Strongly recommended if you rely on your income",
    intro: "If your expenses depend on a regular income, incapacity cover is one of the options I strongly recommend considering. An agreed daily benefit helps make up lost income during both shorter and longer periods of sick leave.",
    coverage: "Cover can include both illness and injury. We will check that your policy includes both causes and suits your occupation and health. A sick note alone does not automatically entitle you to payment under every policy.",
    startTitle: "When does the insurer pay?", starts: ["From day 15", "From day 29", "From day 60"],
    startText: "These are common options. The qualifying period determines how long sick leave must last and the first covered day. The exact duration and availability of retrospective cover depend on the product.",
    retroTitle: "Retrospectively from day 1", retroText: "Once sick leave reaches the agreed minimum duration and policy conditions are met, the insurer also pays for earlier days from its start. A shorter absence does not qualify under this option.",
    followingTitle: "From the selected day onwards", followingText: "Benefits are counted only from the selected day. Earlier days of sick leave are not paid under this cover.",
    exampleTitle: "The same absence. A different number of paid days.", exampleText: "Example: 30 days of sick leave, CZK 500 daily benefit, cover from day 15. We assume the policy conditions are met.",
    retroExample: "Retrospective: 30 × CZK 500", followingExample: "From day 15: 16 × CZK 500", exampleNote: "Retrospective cover does not mean money arrives on day one. It describes the days for which payment becomes due.",
    recommendationTitle: "The setup I usually recommend",
    recommendation: "If you depend on your income and have limited savings, I generally recommend considering cover from day 15 with payment back to day 1, where the product offers it for both illness and injury.",
    price: "If the price difference is small, broader protection may be worthwhile. We will compare the actual price, which depends on the product, age, occupation and health. Larger savings may allow a longer qualifying period.",
    checksTitle: "What else we will check",
    checks: [
      ["Waiting period after taking out cover", "The initial waiting period runs from the start of the policy; the qualifying period concerns each absence. Rules may differ for illness, injury and pregnancy."],
      ["Daily benefit and proof of income", "We will match the benefit to your actual income gap, expenses and savings, and check the insurer’s limits and required documents."],
      ["Exclusions and benefit duration", "We will review pre-existing conditions, possible restrictions for back problems, mental health or pregnancy, and the maximum payment duration. Disability cover complements long-term protection."],
      ["Rules for the self-employed", "Ordinary social insurance payments are not voluntary sickness insurance. We will check state benefit eligibility and the private policy conditions for your work."],
    ],
    calculateCta: "Calculate what I would receive", meetingCta: "Discuss my insurance setup",
    calcTitle: "What would you receive on sick leave?", calcIntro: "An estimate for 2026 separating employer compensation from OSSZ sickness benefits.",
    employment: "Work situation", employee: "Employee", selfEmployed: "Self-employed", period: "Sick leave duration", days: "days",
    gross: "Average gross monthly income", grossHint: "Assessable income over the last 12 months, in CZK.",
    net: "Usual net monthly income", netHint: "Optional. For comparison with what you normally have available for expenses. For the self-employed: after costs, tax and contributions.",
    insured: "I pay voluntary sickness insurance and meet the eligibility conditions.",
    insuredHint: "Self-employed people generally need at least 3 months of participation before sick leave and must not personally carry on their business during it. Statutory exceptions exist.",
    uninsured: "Without eligibility under voluntary sickness insurance, the estimate shows CZK 0 from OSSZ. Self-employed people receive no employer compensation.",
    base: "Average monthly sickness insurance assessment base", baseHint: "In CZK. This is not turnover, profit or the monthly premium. Check your base with CSSA.",
    precision: "Refine employer compensation", hourly: "Average hourly earnings", hourlyHint: "Optional, in CZK/hour. Use the previous quarter’s average for compensation from your payslip or payroll department.",
    workingDays: "Paid working days within the first 14 days", workingDaysHint: "0–14 scheduled days, including holidays eligible for compensation.", hours: "Hours per working day", hoursHint: "At most 24 hours; use the average for varying shifts.",
    estimatedHint: "Without hourly earnings, we use gross pay ÷ 173.33 hours (a 40-hour week). The default schedule is 10 eight-hour days in the first 14 days. Refine these figures for part-time or shift work.",
    invalid: "Enter valid non-negative amounts. Income and hourly earnings must be above 0; the schedule must stay within the stated limits.",
    empty: "Enter your income to see an estimate.", example: "Try an example",
    employer: "Employer", noEmployer: "Self-employed people receive no employer compensation.", employerNote: "Compensation for scheduled hours on days 1–14.", state: "OSSZ", stateNote: "Sickness benefits for calendar days from day 15.", total: "Total for the whole period", totalNote: "Total for the selected duration, not a monthly benefit. Private insurance is excluded.",
    normalIncome: "Usual net income for the same period", gap: "Estimated income shortfall", noGap: "This model shows no positive shortfall against the net income you entered.", addNet: "Enter your net income to see how much you could be missing over this period.",
    breakdown: "How the amount is calculated", periods: ["Days 15–30", "Days 31–60", "Days 61–90"], daily: "CZK / day", reduced: "of the reduced daily assessment base",
    assumptions: "The model uses monthly base × 12 / 365 without excluded days. It assumes ongoing ordinary eligibility and omits special cases such as pension recipients. Net income is compared in 30-day months. Actual amounts depend on employer and CSSA records.",
    sources: "Rules and sources", privateSource: "Example cover options · ČPP", privacy: "Amounts you enter are used only for the calculation in this window.",
  },
  uk: {
    title: "Тимчасова непрацездатність", kicker: "Захист вашого доходу", close: "Закрити деталі непрацездатності",
    tabs: "Зміст вікна", overview: "Як працює страхування", calculator: "Розрахувати дохід", detail: "Деталі покриття та розрахунок доходу",
    badge: "Особливо рекомендовано, якщо ви залежите від доходу",
    intro: "Якщо ваші витрати залежать від регулярного доходу, страхування непрацездатності належить до покриттів, які я наполегливо рекомендую розглянути. Узгоджена щоденна виплата допомагає компенсувати втрату доходу під час коротшої та тривалої непрацездатності.",
    coverage: "Покриття можна оформити на випадок хвороби та травми. Ми перевіримо, чи договір охоплює обидві причини та відповідає вашій роботі й стану здоров’я. Сам лікарняний не означає автоматичного права на виплату за будь-яким договором.",
    startTitle: "Відколи страхова компанія платить?", starts: ["Від 15-го дня", "Від 29-го дня", "Від 60-го дня"],
    startText: "Це поширені варіанти. Мінімальний період непрацездатності визначає, скільки вона має тривати та з якого дня можливі виплати. Точний строк і можливість виплат від першого дня залежать від продукту.",
    retroTitle: "Заднім числом від 1-го дня", retroText: "Коли непрацездатність досягне узгодженої мінімальної тривалості та виконано умови договору, страхова компанія оплатить також попередні дні від її початку. Коротша непрацездатність за цим варіантом не оплачується.",
    followingTitle: "Від обраного дня надалі", followingText: "Виплати обчислюються лише від обраного дня. Попередні дні непрацездатності за цим покриттям не оплачуються.",
    exampleTitle: "Однакова непрацездатність. Різна кількість оплачених днів.", exampleText: "Приклад: 30 днів непрацездатності, щоденна виплата 500 Kč, варіант від 15-го дня. Припускаємо виконання умов договору.",
    retroExample: "Від початку: 30 × 500 Kč", followingExample: "Від 15-го дня: 16 × 500 Kč", exampleNote: "Виплата від першого дня не означає надходження грошей одразу. Йдеться про дні, за які виникає право на виплату.",
    recommendationTitle: "Яке налаштування я зазвичай рекомендую",
    recommendation: "Якщо ви залежите від доходу та маєте невеликий резерв, я зазвичай рекомендую розглянути варіант від 15-го дня з виплатою від 1-го дня, якщо продукт пропонує його для хвороб і травм.",
    price: "Якщо різниця в ціні невелика, ширший захист може бути доцільним. Ми порівняємо конкретну вартість: вона залежить від продукту, віку, професії та здоров’я. Більший резерв може дозволити довший мінімальний період.",
    checksTitle: "Що ще ми перевіримо",
    checks: [
      ["Період очікування після оформлення", "Початковий період очікування відраховується від початку страхування, а мінімальна тривалість стосується конкретного лікарняного. Правила для хвороби, травми чи вагітності можуть відрізнятися."],
      ["Розмір виплати та підтвердження доходу", "Щоденну суму підберемо за фактичною втратою доходу, витратами та резервами. Перевіримо ліміти й документи, які вимагатиме страхова компанія."],
      ["Виключення та тривалість виплат", "Перевіримо попередні захворювання, можливі обмеження щодо спини, психічного здоров’я чи вагітності та максимальний строк виплат. Тривалий захист доповнює страхування інвалідності."],
      ["Правила для самозайнятих", "Звичайні соціальні внески не є добровільним страхуванням на випадок хвороби. Перевіримо право на державні виплати й умови приватного страхування для вашої діяльності."],
    ],
    calculateCta: "Розрахувати майбутні виплати", meetingCta: "Обговорити моє страхування",
    calcTitle: "Скільки ви отримаєте на лікарняному?", calcIntro: "Орієнтовний розрахунок на 2026 рік окремо показує компенсацію роботодавця та лікарняні від OSSZ.",
    employment: "Зайнятість", employee: "Працівник", selfEmployed: "Самозайнята особа", period: "Тривалість непрацездатності", days: "днів",
    gross: "Середній місячний дохід до оподаткування", grossHint: "Дохід, з якого сплачуються внески, за останні 12 місяців, у Kč.",
    net: "Звичайний чистий місячний дохід", netHint: "Необов’язково. Для порівняння із сумою на повсякденні витрати. Для самозайнятих — після витрат, податків і внесків.",
    insured: "Я сплачую добровільне страхування на випадок хвороби та виконую умови права на виплату.",
    insuredHint: "Для самозайнятих зазвичай потрібна участь щонайменше 3 місяці до непрацездатності; під час неї не можна особисто вести свою діяльність. Існують законні винятки.",
    uninsured: "Без права на лікарняні за добровільним страхуванням модель показує 0 Kč від OSSZ. Самозайняті не отримують компенсації від роботодавця.",
    base: "Середня місячна база страхування на випадок хвороби", baseHint: "У Kč. Це не оборот, прибуток чи місячний внесок. Базу можна уточнити в ЧССЗ.",
    precision: "Уточнити компенсацію роботодавця", hourly: "Середній погодинний заробіток", hourlyHint: "Необов’язково, Kč/год. Середній заробіток для компенсацій за попередній квартал з розрахункового листа або бухгалтерії.",
    workingDays: "Оплачувані робочі дні в перші 14 днів", workingDaysHint: "0–14 днів за графіком, включно зі святами з компенсацією.", hours: "Годин за робочий день", hoursHint: "Не більше 24 год; для різних змін — середнє.",
    estimatedHint: "Без погодинного заробітку ділимо місячний дохід на 173,33 год (40 год на тиждень). Типовий графік — 10 днів по 8 год у перші 14 днів. Для неповної зайнятості чи змін уточніть дані.",
    invalid: "Введіть коректні невід’ємні суми. Дохід і погодинний заробіток мають бути більшими за 0, а графік — у зазначених межах.",
    empty: "Вкажіть дохід, щоб побачити орієнтовний розрахунок.", example: "Спробувати приклад",
    employer: "Роботодавець", noEmployer: "Самозайняті не отримують компенсації роботодавця.", employerNote: "Компенсація за години за графіком у 1–14-й день.", state: "OSSZ", stateNote: "Лікарняні за календарні дні від 15-го дня.", total: "Разом за весь період", totalNote: "Сума за обрану тривалість, а не місячна виплата. Без приватного страхування.",
    normalIncome: "Звичайний чистий дохід за той самий період", gap: "Орієнтовна втрата доходу", noGap: "У цій моделі немає додатної різниці порівняно із зазначеним чистим доходом.", addNet: "Додайте чистий дохід, щоб побачити, скільки вам могло б бракувати за цей період.",
    breakdown: "Як складається сума", periods: ["15–30-й день", "31–60-й день", "61–90-й день"], daily: "Kč / день", reduced: "зі зменшеної денної бази",
    assumptions: "Модель використовує місячну базу × 12 / 365 без виключених днів. Припускає звичайне чинне право на виплати та не враховує особливі випадки, наприклад пенсіонерів. Чистий дохід порівнюється за 30-денними місяцями. Фактичні суми залежать від даних роботодавця й ЧССЗ.",
    sources: "Правила та джерела", privateSource: "Приклад варіантів покриття · ČPP", privacy: "Введені суми використовуються лише для розрахунку в цьому вікні.",
  },
} as const;
