import type { PdfLanguage } from "./lifeInsuranceShared";

export const DISABILITY_PENSION_COPY = {
  cs: {
    average: "Průměrný státní důchod",
    monthly: "měsíčně",
    privateCover: "Soukromé zajištění",
    privateAnnuity: "Plánovaná soukromá renta / měsíc",
    reference: "Průměry samostatně vyplácených invalidních důchodů v ČR",
    asOf: "stav k",
    source: "Zdroj",
    note: "Skutečný důchod klienta může být jiný. Uvedené průměry slouží pro představu a neodečítají se od návrhu soukromého krytí.",
  },
  en: {
    average: "Average state pension",
    monthly: "per month",
    privateCover: "Private provision",
    privateAnnuity: "Planned private annuity / month",
    reference: "Average standalone disability pensions in the Czech Republic",
    asOf: "as of",
    source: "Source",
    note: "The client's actual pension may differ. These averages are for reference and are not deducted from the proposed private cover.",
  },
  uk: {
    average: "Середня державна пенсія",
    monthly: "на місяць",
    privateCover: "Приватне забезпечення",
    privateAnnuity: "Запланована приватна рента / місяць",
    reference: "Середні окремо виплачувані пенсії по інвалідності в Чехії",
    asOf: "станом на",
    source: "Джерело",
    note: "Фактична пенсія клієнта може відрізнятися. Ці середні суми наведено для довідки й не віднімаються від запропонованого приватного покриття.",
  },
  ne: {
    average: "औसत सरकारी पेन्सन",
    monthly: "प्रति महिना",
    privateCover: "निजी व्यवस्था",
    privateAnnuity: "योजनाबद्ध निजी मासिक आय",
    reference: "चेक गणतन्त्रमा छुट्टै भुक्तानी गरिने अपाङ्गता पेन्सनको औसत",
    asOf: "तथ्याङ्क मिति",
    source: "स्रोत",
    note: "ग्राहकको वास्तविक पेन्सन फरक हुन सक्छ। यी औसत रकम जानकारीका लागि मात्र हुन् र प्रस्तावित निजी सुरक्षाबाट घटाइँदैनन्।",
  },
  hi: {
    average: "औसत सरकारी पेंशन",
    monthly: "प्रति माह",
    privateCover: "निजी व्यवस्था",
    privateAnnuity: "नियोजित निजी मासिक आय",
    reference: "चेक गणराज्य में अलग से भुगतान की जाने वाली विकलांगता पेंशन का औसत",
    asOf: "आँकड़ों की तारीख",
    source: "स्रोत",
    note: "ग्राहक की वास्तविक पेंशन अलग हो सकती है। ये औसत राशियाँ केवल जानकारी के लिए हैं और प्रस्तावित निजी सुरक्षा से घटाई नहीं जातीं।",
  },
} satisfies Record<PdfLanguage, Record<string, string>>;
