import type { PdfLanguage } from "./lifeInsuranceShared";

export const PENSION_PLAN_COPY = {
  cs: {
    estimate: "Osobní odhad státního důchodu",
    gross: "Hrubá mzda jako odhad OVZ",
    ovz: "Osobní vyměřovací základ",
    years: "Celé započtené roky včetně dopočtené doby",
    minimum: { ordinary: "běžné minimum", insured15: "zvýšené minimum: 15 let bez náhradních dob", under28: "zvýšené minimum: osoba pod 28 let se splněnými podmínkami" },
    reference: "Osobní odhad je pouze pro přehled a neodečítá se od soukromého krytí.",
    details: "Jak je důchod odhadnutý?",
    assumptions: "Orientační výpočet podle pravidel roku 2026. Skutečný nárok a výši důchodu určuje ČSSZ.",
  },
  en: {
    estimate: "Personal state pension estimate",
    gross: "Gross pay used to estimate the assessment base",
    ovz: "Personal assessment base",
    years: "Full credited years including the credited future period",
    minimum: { ordinary: "ordinary minimum", insured15: "higher minimum: 15 years excluding substitute periods", under28: "higher minimum: under 28 with qualifying conditions met" },
    reference: "The personal estimate is for reference only and is not deducted from private cover.",
    details: "How is the pension estimated?",
    assumptions: "Indicative calculation under 2026 rules. Actual entitlement and pension amount are determined by ČSSZ.",
  },
  uk: {
    estimate: "Особиста оцінка державної пенсії",
    gross: "Валова зарплата як оцінка бази",
    ovz: "Особиста розрахункова база",
    years: "Повні зараховані роки, включно з майбутнім періодом",
    minimum: { ordinary: "звичайний мінімум", insured15: "підвищений мінімум: 15 років без замінних періодів", under28: "підвищений мінімум: особа до 28 років за виконання умов" },
    reference: "Особиста оцінка наводиться для довідки і не віднімається від приватного покриття.",
    details: "Як оцінюється пенсія?",
    assumptions: "Орієнтовний розрахунок за правилами 2026 року. Фактичне право та розмір пенсії визначає ČSSZ.",
  },
  ne: {
    estimate: "व्यक्तिगत सरकारी पेन्सनको अनुमान",
    gross: "आधार अनुमानका लागि कुल तलब",
    ovz: "व्यक्तिगत मूल्याङ्कन आधार",
    years: "भविष्यको गणना गरिएको अवधि सहित पूरा वर्ष",
    minimum: { ordinary: "साधारण न्यूनतम", insured15: "उच्च न्यूनतम: प्रतिस्थापन अवधि बाहेक १५ वर्ष", under28: "उच्च न्यूनतम: आवश्यक सर्त पूरा गरेको २८ वर्षमुनिको व्यक्ति" },
    reference: "व्यक्तिगत अनुमान जानकारीका लागि मात्र हो र निजी सुरक्षाबाट घटाइँदैन।",
    details: "पेन्सनको अनुमान कसरी गरिन्छ?",
    assumptions: "२०२६ को नियमअनुसार अनुमानित गणना। वास्तविक अधिकार र पेन्सन रकम ČSSZ ले निर्धारण गर्छ।",
  },
  hi: {
    estimate: "व्यक्तिगत सरकारी पेंशन का अनुमान",
    gross: "आधार के अनुमान हेतु सकल वेतन",
    ovz: "व्यक्तिगत निर्धारण आधार",
    years: "भविष्य की गणना की गई अवधि सहित पूरे वर्ष",
    minimum: { ordinary: "सामान्य न्यूनतम", insured15: "उच्च न्यूनतम: वैकल्पिक अवधियों को छोड़कर १५ वर्ष", under28: "उच्च न्यूनतम: आवश्यक शर्तों सहित २८ वर्ष से कम आयु" },
    reference: "व्यक्तिगत अनुमान केवल जानकारी के लिए है और निजी सुरक्षा से नहीं घटाया जाता।",
    details: "पेंशन का अनुमान कैसे लगाया जाता है?",
    assumptions: "२०२६ के नियमों के अनुसार अनुमानित गणना। वास्तविक अधिकार और पेंशन राशि ČSSZ तय करता है।",
  },
} satisfies Record<PdfLanguage, unknown>;
