export const VEHICLE_COPY = {
  cs: {
    category: "Pojištění vozidel",
    reviewKicker: "Nezávazná kontrola smlouvy",
    reviewTitle: "Nižší cena a širší krytí mohou jít spolu.",
    reviewExperience: "Ve většině případů se mi podaří pojištění zlevnit a zároveň rozšířit krytí.",
    reviewNote: "Konkrétní možnosti zjistíme porovnáním vaší smlouvy s aktuálními nabídkami.",
    reviewSteps: [
      ["Projdeme vaši smlouvu", "Zkontrolujeme cenu, limity, spoluúčast, připojištění i asistenci."],
      ["Porovnáme alternativy", "Podíváme se, zda jiné nastavení nebo jiná pojišťovna nabídne za vaše peníze víc."],
      ["Rozhodnutí je na vás", "Srozumitelně vysvětlím rozdíly. Ke změně pojištění se kontrolou nezavazujete."],
    ],
    reviewFeatures: ["Cena", "Krytí", "Asistence"],
    reviewPrepare: "Pro kontrolu si připravte stávající pojistnou smlouvu a údaje o vozidle.",
    experienceLabel: "Z mé praxe",
    factGlassNumber: "1 ze 4",
    factGlassDetail: "škod na autě se podle Kooperativy týká čelního skla.",
    factsLabel: "Proč záleží na rozsahu krytí",
    vehicleAlt: "Tyrkysové auto ve 3D",
    heroTitle: "Vaše auto.",
    heroAccent: "Výhodnější pojištění?",
    heroLead:
      "Pojďme udělat nezávaznou kontrolu vaší stávající smlouvy. Zjistíme, jak je nastavená, a podíváme se, zda pro vás najdeme levnější a efektivnější alternativu.",
    heroCta: "Co ve smlouvě zkontrolujeme",
    factWildlifeValue: "18 112",
    factWildlifeLabel: "evidovaných střetů se zvěří od října 2025 do března 2026",
    source: "Zdroj",
    coverageKicker: "Co řeší samotné povinné ručení",
    coverageTitle: "Zákonná povinnost není totéž co ochrana vlastního auta.",
    coverageLead:
      "Povinné ručení hradí újmu, kterou provozem vozidla způsobíte ostatním. Pro vlastní vůz je potřeba zvolit odpovídající havarijní pojištění nebo připojištění.",
    coverageHeadEvent: "Co se stalo",
    coverageHeadBase: "Samotné povinné ručení",
    coverageHeadBetter: "Dobře nastavené krytí",
    coverageRows: [
      ["Způsobíte škodu jinému", "Kryje škodu poškozeného", "Dostatečný limit odpovědnosti"],
      ["Poškodíte vlastní auto", "Vlastní škodu nekryje", "Havarijní pojištění"],
      ["Kamínek poškodí sklo", "Bez připojištění nekryje", "Skla s reálným limitem"],
      ["Střetnete se se zvířetem", "Vlastní škodu nekryje", "Střet se zvířetem nebo havarijní"],
      ["Porucha daleko od domova", "Jen dle rozsahu asistence", "Odtah, oprava, náhradní vůz"],
    ],
    protectionKicker: "Rozsah ochrany",
    protectionTitle: "Čtyři oblasti, které stojí za kontrolu.",
    protectionCards: [
      ["Havarijní pojištění", "Chrání hodnotu vašeho auta při vlastní chybě, vandalismu, odcizení nebo živlu podle sjednaného rozsahu.", "Důležitá je hodnota vozu, spoluúčast a rozsah rizik — ne pouze jeho stáří."],
      ["Skla", "Limit musí odpovídat skutečné ceně skla, montáže a případné kalibrace kamer a senzorů.", "Ověřte, zda jsou kryta všechna výhledová skla, panoramatická střecha i zrcátka."],
      ["Střet a poškození zvířetem", "Střet se zvířetem a poškození zaparkovaného vozu zvířetem mohou být dvě rozdílná rizika.", "Nestačí jen název připojištění — rozhoduje definice události a limit."],
      ["Asistenční služby", "Telefonní číslo na kartičce ještě neznamená, že máte odtah tam, kam potřebujete.", "Porovnávejte limity, územní platnost a pomoc po poruše, nehodě i chybě řidiče."],
    ],
    assistanceKicker: "Asistence, která opravdu pomůže",
    assistanceTitle: "Pomoc na cestách začíná dobře nastavenou asistencí.",
    assistanceLead:
      "Základní varianta může stačit ve městě. Na dálnici nebo v zahraničí ale rozhodují konkrétní kilometry, finanční limity a navazující pomoc.",
    assistanceItems: [
      "oprava vozidla na místě",
      "odtah bez nízkého kilometrového limitu",
      "náhradní vozidlo po dobu opravy",
      "ubytování nebo pokračování v cestě",
      "repatriace vozidla ze zahraničí",
      "pomoc při defektu, záměně paliva či ztrátě klíčů",
    ],
    assistanceQuestion: "Víte, kolik kilometrů odtahu vaše smlouva skutečně zaplatí?",
    setupKicker: "Pojďme se na to podívat",
    setupTitle: "Zjistěte, jestli vaše smlouva může nabídnout víc.",
    setupText:
      "Zohledníme hodnotu a stáří auta, roční nájezd, způsob parkování, řidiče, cesty do zahraničí i částku, kterou jste ochotni nést sami.",
    setupStrong:
      "Porovnáme nejen cenu, ale také limity, spoluúčast, výluky, servisní síť a skutečný rozsah asistence.",
    meetingCta: "Nezávazně zkontrolovat smlouvu",
    meetingTitle: "Domluvme si kontrolu smlouvy",
    meetingDescription: "Nechte na sebe kontakt. Společně projdeme současnou smlouvu a možnosti výhodnějšího nastavení.",
    closeForm: "Zavřít formulář",
    submitted: "Žádost byla odeslána.",
    thankYou: "Děkujeme, brzy se vám ozveme.",
    footer:
      "Konkrétní rozsah krytí, limity, výluky a spoluúčast se vždy řídí pojistnou smlouvou a pojistnými podmínkami vybraného produktu.",
  },
  en: {
    category: "Vehicle insurance",
    reviewKicker: "No-obligation policy review",
    reviewTitle: "A lower price and broader cover can go together.",
    reviewExperience: "In most cases, I manage to reduce the premium while broadening the cover.",
    reviewNote: "We will identify your options by comparing your policy with current offers.",
    reviewSteps: [
      ["Review your current policy", "We check the price, limits, excess, additional cover and assistance."],
      ["Compare alternatives", "We look at whether a different arrangement or insurer could offer more for your money."],
      ["The choice stays yours", "I will explain the differences clearly. A review does not commit you to changing your insurance."],
    ],
    reviewFeatures: ["Price", "Cover", "Assistance"],
    reviewPrepare: "Have your current insurance policy and vehicle details ready for the review.",
    experienceLabel: "From my experience",
    factGlassNumber: "1 in 4",
    factGlassDetail: "vehicle claims involve the windscreen, according to Kooperativa.",
    factsLabel: "Why the scope of cover matters",
    vehicleAlt: "A teal car rendered in 3D",
    heroTitle: "Your car.",
    heroAccent: "Better-value insurance?",
    heroLead:
      "Let’s review your current policy with no obligation. We will check how it is set up and see whether we can find a less expensive alternative that better meets your needs.",
    heroCta: "What we check in your policy",
    factWildlifeValue: "18,112",
    factWildlifeLabel: "recorded wildlife collisions from October 2025 to March 2026",
    source: "Source",
    coverageKicker: "What compulsory liability covers",
    coverageTitle: "A legal obligation is not the same as protecting your own car.",
    coverageLead:
      "Liability insurance pays for harm you cause to others while operating the vehicle. Your own car needs suitable comprehensive or additional cover.",
    coverageHeadEvent: "What happened",
    coverageHeadBase: "Liability only",
    coverageHeadBetter: "Well-arranged cover",
    coverageRows: [
      ["You damage someone else's property", "Covers the injured party", "An adequate liability limit"],
      ["You damage your own car", "Does not cover your loss", "Comprehensive insurance"],
      ["A stone damages the glass", "Not without extra cover", "Glass cover with a realistic limit"],
      ["You collide with an animal", "Does not cover your car", "Animal collision or comprehensive cover"],
      ["You break down far from home", "Only within assistance limits", "Recovery, repair and replacement car"],
    ],
    protectionKicker: "Scope of protection",
    protectionTitle: "Four areas worth checking.",
    protectionCards: [
      ["Comprehensive insurance", "Protects the value of your car after an at-fault accident, vandalism, theft or natural event, depending on the selected scope.", "The car's value, excess and covered risks matter more than age alone."],
      ["Glass", "The limit should reflect the real cost of the glass, installation and calibration of cameras and sensors.", "Check whether all windows, the panoramic roof and mirrors are covered."],
      ["Animal collision and damage", "A collision with an animal and animal damage to a parked car may be two different insured risks.", "The event definition and limit matter more than the add-on's name."],
      ["Roadside assistance", "A phone number on your card does not guarantee recovery to where you need to go.", "Compare limits, territorial scope and help after breakdowns, accidents and driver errors."],
    ],
    assistanceKicker: "Assistance that actually helps",
    assistanceTitle: "Help on the road starts with the right assistance cover.",
    assistanceLead:
      "Basic assistance may be enough in town. On a motorway or abroad, mileage, financial limits and onward support become decisive.",
    assistanceItems: [
      "repair at the roadside",
      "recovery without a low mileage cap",
      "replacement car during repairs",
      "accommodation or continuation of the journey",
      "vehicle repatriation from abroad",
      "help with a puncture, wrong fuel or lost keys",
    ],
    assistanceQuestion: "Do you know how many recovery kilometres your policy will actually pay for?",
    setupKicker: "Let’s take a look together",
    setupTitle: "Find out whether your policy could offer more.",
    setupText:
      "We consider the vehicle's value and age, annual mileage, parking, drivers, travel abroad and the loss you are prepared to bear yourself.",
    setupStrong:
      "We compare not only price, but also limits, excess, exclusions, repair networks and the real assistance scope.",
    meetingCta: "Request a no-obligation review",
    meetingTitle: "Arrange a policy review",
    meetingDescription: "Leave your details. We will go through your current policy and the options for a better arrangement together.",
    closeForm: "Close form",
    submitted: "Your request has been sent.",
    thankYou: "Thank you. We will be in touch soon.",
    footer:
      "The exact scope, limits, exclusions and excess are always governed by the policy and terms of the selected insurance product.",
  },
  uk: {
    category: "Страхування автомобіля",
    reviewKicker: "Перевірка поліса без зобов’язань",
    reviewTitle: "Нижча ціна та ширше покриття можуть поєднуватися.",
    reviewExperience: "У більшості випадків мені вдається знизити вартість страхування й водночас розширити покриття.",
    reviewNote: "Конкретні можливості визначимо, порівнявши ваш поліс з актуальними пропозиціями.",
    reviewSteps: [
      ["Переглянемо ваш поліс", "Перевіримо ціну, ліміти, франшизу, додаткове покриття й асистанс."],
      ["Порівняємо альтернативи", "З’ясуємо, чи інші умови або інша страхова компанія можуть запропонувати більше за ваші гроші."],
      ["Рішення залишається за вами", "Зрозуміло поясню відмінності. Перевірка не зобов’язує вас змінювати страхування."],
    ],
    reviewFeatures: ["Ціна", "Покриття", "Асистанс"],
    reviewPrepare: "Для перевірки підготуйте чинний страховий поліс і дані автомобіля.",
    experienceLabel: "З мого досвіду",
    factGlassNumber: "1 з 4",
    factGlassDetail: "страхових подій з авто стосується лобового скла, за даними Kooperativa.",
    factsLabel: "Чому важливий обсяг покриття",
    vehicleAlt: "Бірюзовий автомобіль у 3D",
    heroTitle: "Ваше авто.",
    heroAccent: "Вигідніше страхування?",
    heroLead:
      "Давайте перевіримо ваш чинний поліс без жодних зобов’язань. Розберемося в його умовах і подивимося, чи можна знайти дешевшу альтернативу, яка краще відповідає вашим потребам.",
    heroCta: "Що ми перевіримо в полісі",
    factWildlifeValue: "18 112",
    factWildlifeLabel: "зафіксованих зіткнень із тваринами з жовтня 2025 до березня 2026 року",
    source: "Джерело",
    coverageKicker: "Що покриває обов’язкове страхування",
    coverageTitle: "Виконати вимогу закону — не те саме, що захистити власне авто.",
    coverageLead:
      "Страхування відповідальності відшкодовує збитки, завдані іншим. Для власного автомобіля потрібне відповідне каско або додаткове покриття.",
    coverageHeadEvent: "Що сталося",
    coverageHeadBase: "Лише автоцивілка",
    coverageHeadBetter: "Правильно налаштований захист",
    coverageRows: [
      ["Ви завдали шкоди іншому", "Покриває збиток потерпілого", "Достатній ліміт відповідальності"],
      ["Ви пошкодили власне авто", "Не покриває ваш збиток", "Каско"],
      ["Камінь пошкодив скло", "Не покриває без доповнення", "Скло з реальним лімітом"],
      ["Ви зіткнулися з твариною", "Не покриває ваше авто", "Зіткнення з твариною або каско"],
      ["Поломка далеко від дому", "Лише в межах асистансу", "Евакуація, ремонт і підмінне авто"],
    ],
    protectionKicker: "Обсяг захисту",
    protectionTitle: "Чотири сфери, які варто перевірити.",
    protectionCards: [
      ["Каско", "Захищає вартість авто при аварії з вашої вини, вандалізмі, викраденні або стихії відповідно до обраного покриття.", "Вартість авто, франшиза та ризики важливіші, ніж лише його вік."],
      ["Скло", "Ліміт має відповідати реальній ціні скла, монтажу та калібрування камер і датчиків.", "Перевірте покриття всіх вікон, панорамного даху та дзеркал."],
      ["Зіткнення і пошкодження твариною", "Зіткнення з твариною та пошкодження припаркованого авто можуть бути різними ризиками.", "Вирішальними є визначення події та ліміт, а не лише назва доповнення."],
      ["Допомога в дорозі", "Номер телефону на картці ще не гарантує евакуацію туди, куди вам потрібно.", "Порівнюйте ліміти, територію та допомогу після поломки, аварії чи помилки водія."],
    ],
    assistanceKicker: "Допомога, яка справді працює",
    assistanceTitle: "Допомога в дорозі починається з правильно обраного асистансу.",
    assistanceLead:
      "Базового варіанта може вистачити в місті. На автомагістралі чи за кордоном вирішують кілометри, фінансові ліміти та подальша допомога.",
    assistanceItems: [
      "ремонт автомобіля на місці",
      "евакуація без низького ліміту кілометрів",
      "підмінне авто на час ремонту",
      "проживання або продовження подорожі",
      "репатріація автомобіля з-за кордону",
      "допомога при проколі, неправильному пальному чи втраті ключів",
    ],
    assistanceQuestion: "Чи знаєте ви, скільки кілометрів евакуації реально оплатить ваш поліс?",
    setupKicker: "Давайте розглянемо разом",
    setupTitle: "Дізнайтеся, чи може ваш поліс запропонувати більше.",
    setupText:
      "Врахуємо вартість і вік авто, річний пробіг, паркування, водіїв, поїздки за кордон і суму, яку ви готові покрити самостійно.",
    setupStrong:
      "Порівняємо не лише ціну, а й ліміти, франшизу, винятки, мережу сервісів і реальний обсяг допомоги.",
    meetingCta: "Перевірити поліс без зобов’язань",
    meetingTitle: "Домовимося про перевірку поліса",
    meetingDescription: "Залиште контакти. Разом переглянемо чинний поліс і можливості вигідніших умов.",
    closeForm: "Закрити форму",
    submitted: "Запит надіслано.",
    thankYou: "Дякуємо, незабаром ми з вами зв’яжемося.",
    footer:
      "Точний обсяг покриття, ліміти, винятки та франшиза завжди визначаються договором і умовами обраного страхового продукту.",
  },
} as const;
